#!/usr/bin/env python
import os, os.path as path

Import("tiBuild")
Import('build')

sources = Glob('*.cpp')+Glob('irc/*.cpp')+Glob('http/*.cpp')

env = tiBuild.env.Clone();
env.Append(CPPDEFINES = ('TITANIUM_NETWORK_API_EXPORT', 1))

if tiBuild.is_osx():
	tiBuild.add_thirdparty(env, 'poco', True)
	env.Append(LIBS=['kroll'])
	env.Append(FRAMEWORKS=['SystemConfiguration'])
	sources+=Glob('osx/*.mm')
else:
	tiBuild.add_thirdparty(env, 'poco')

if tiBuild.is_win32():
    env.Append(CCFLAGS=['/MD'])
    env.Append(LIBS=['wsock32','ws2_32', 'ole32', 'comsuppw', 'wbemuuid'])
    env.Append(CPPDEFINES = ('WIN32_LEAN_AND_MEAN',1))
    sources += Glob("win32/*.cpp")

s = env.SharedLibrary(target = tiBuild.dir + '/tinetworkmodule', source = sources)


