#!/usr/bin/env python
import os, os.path as path

Import("tiBuild")
Import('build')

tiBuild.add_thirdparty(build.env, 'poco')

env = tiBuild.env.Clone();
env.Append(CPPDEFINES = ('TITANIUM_NETWORK_API_EXPORT', 1))

if tiBuild.is_win32():
    env.Append(CCFLAGS=['/MD'])
    env.Append(LIBS=['wsock32','ws2_32'])
    env.Append(CPPDEFINES = ('WIN32_LEAN_AND_MEAN',1))

s = env.SharedLibrary(target = tiBuild.dir + '/tinetworkmodule', source = Glob('*.cpp')+Glob('irc/*.cpp'))


