#!/usr/bin/env python
import os, os.path as path

Import("tiBuild")
Import('build')

env = tiBuild.env.Clone();

if tiBuild.is_osx():
	tiBuild.add_thirdparty(env, 'poco', True)
	env.Append(LIBS=['kroll','tiappmodule'])
	env.Append(FRAMEWORKS = ['Cocoa'])
else:
	tiBuild.add_thirdparty(env, 'poco')

env.Append(CPPDEFINES = ('TITANIUM_FILESYSTEM_API_EXPORT', 1))
env.Append(CPPPATH = ['#kroll','%s/modules/ti.App' % build.titanium_source_dir])
env.Append(LIBPATH=[path.join(build.dir, 'modules', 'ti.App')])


if tiBuild.is_win32():
    env.Append(CCFLAGS=['/MD'])
    env.Append(LIBS=['shell32', 'user32', 'comdlg32', 'ole32'])
    env.Append(CPPDEFINES = ('WIN32_LEAN_AND_MEAN',1))


s = env.SharedLibrary(target = tiBuild.dir + '/tifilesystemmodule', source = Glob('*.cpp'))
