#!/usr/bin/env python
import os, os.path as path

Import("tiBuild")
Import('build')

tiBuild.add_thirdparty(build.env, 'poco')

env = tiBuild.env.Clone();
env.Append(CPPDEFINES = {'TITANIUM_FILESYSTEM_API_EXPORT' : 1})
env.Append(CPPPATH = ['#kroll'])

if tiBuild.is_win32():
    env.Append(CCFLAGS=['/MD'])


s = env.SharedLibrary(target = tiBuild.dir + '/tifilesystemmodule', source = Glob('*.cpp'))
