#!/usr/bin/env python
import os.path as path

Import('build')
csbuilder = Builder(action = 'devenv $SOURCE /build Release')

Env = build.env.Clone(BUILDERS = {'CSProgram': csbuilder})
Env.Append(CPPPATH=[build.kroll_source_dir+'/api'])

p = Env.CSProgram('bin/Release/Installer.exe', 'Installer.sln')
Env.AddPostAction(p, Copy(build.dir+'/tinstaller/Installer.exe', build.titanium_source_dir+'/installation/net_installer/win32/bin/Release/Installer.exe'))

#s = Env.Program(build.dir + '/installer', Glob('*.m')+[build.dir+'/api/file_utils.os'])
