#!/usr/bin/env python
import os

Import("tiBuild")
Import('build')

env = tiBuild.env.Clone();
env.Append(CPPDEFINES = ('TITANIUM_DATABASE_API_EXPORT', 1))
env.Append(CPPPATH = ['#kroll'])


s = env.SharedLibrary(target = tiBuild.dir + '/tidatabasemodule', source = Glob('*.cpp'))
