#!/usr/bin/env python
Import('build')
import os

modules = ['ti.App', 'ti.Window','ti.Network','ti.Filesystem','ti.Media','ti.Desktop','ti.Menu']

if build.is_osx():
	modules.append('ti.Growl')
#
for module in modules:
	module_dir = build.dir + '/modules/' + module
	SConscript(module+'/SConscript', build_dir=module_dir, duplicate=0)
	out_dir = os.path.join(build.dir, 'modules', module)
	script = os.path.join(build.kroll_build_dir, 'module.py')
	os.system('%s %s %s %s' % (script, build.dir, out_dir, build.os))

