#!/usr/bin/env python
Import('tiBuild')

modules = ['ti.App', 'ti.Window','ti.Network','ti.Filesystem','ti.Media','ti.Desktop','ti.Menu']

if tiBuild.is_osx():
	modules.append('ti.Growl')
#
for module in modules:
	module_dir = tiBuild.dir + '/modules/' + module
	SConscript(module+'/SConscript', build_dir=module_dir, duplicate=0)
	out_dir = os.path.join(build.abstopdir,'modules',module)
	script = os.path.join(build.krollabsdir,'build','module.py')
	os.system(script+' '+build.dir+' '+out_dir+' '+build.os)
