#!/usr/bin/env python
Import('build')
import os

modules = ['ti.App', 'ti.UI', 'ti.Network',
           'ti.Filesystem', 'ti.Media', 'ti.Desktop',
           'ti.Platform', 'ti.Process']

if build.is_osx() or build.is_win32():
	modules.append('ti.Growl')
#
for module in modules:
	module_dir = os.path.join(build.dir,'modules',module)
	SConscript(os.path.join(module,'SConscript'), build_dir=module_dir, duplicate=0)
	out_dir = os.path.join(build.dir, 'modules', module)
	script = os.path.join(build.kroll_build_dir, 'module.py')
	os.system('python "%s" "%s" "%s" "%s"' % (script, build.dir, out_dir, build.os))

