#!/usr/bin/env python
import os

Import("tiBuild")
Import('build')

tiBuild.add_thirdparty(build.env, 'poco')

env = tiBuild.env.Clone();
env.Append(CPPDEFINES = {'TITANIUM_PROCESS_API_EXPORT' : 1})
env.Append(CPPPATH = ['#kroll'])


s = env.SharedLibrary(target = tiBuild.dir + '/tiprocessmodule', source = Glob('*.cpp'))
