#!/usr/bin/env python
import os.path as path

Import('build')

Env = build.env.Clone()
Env.Append(LIBS=['curl'])
Env.ParseConfig('pkg-config --cflags --libs gtk+-2.0 gdk-2.0 gthread-2.0')
#Env.Append(CPPFLAGS=['-Wno-error']) # turn off warnings, CURLHandle has a lot

sources = Glob('*.cpp')
out = path.join(build.runtime_build_dir, 'installer', 'installer')
i = Env.Program(out, Glob('*.cpp') + [build.kroll_source_dir + '/api/file_utils.cpp'])
build.require(i)
