// Copyright 2007, Google Inc.
//
// Redistribution and use in source and binary forms, with or without 
// modification, are permitted provided that the following conditions are met:
//
//  1. Redistributions of source code must retain the above copyright notice, 
//     this list of conditions and the following disclaimer.
//  2. Redistributions in binary form must reproduce the above copyright notice,
//     this list of conditions and the following disclaimer in the documentation
//     and/or other materials provided with the distribution.
//  3. Neither the name of Google Inc. nor the names of its contributors may be
//     used to endorse or promote products derived from this software without
//     specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
// WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF 
// MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
// EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
// OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR 
// OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF 
// ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

import "oaidl.idl";
import "ocidl.idl";

// Defines the COM interface implemented by our modal dialog which hosts the
// browser control. We need a COM object for two reasons:
// - Interacting with the browser control requires implementing various COM
//   interfaces.
// - We interact with the JavaScript inside the dialog by implementing
//   IDispatch, which it calls.
[
  object,
  uuid(5D437BB7-8634-46D2-AB33-F854034C73D6),
  dual,
  nonextensible,
  pointer_default(unique)
]
interface HtmlDialogHostInterface : IDispatch {
  // Called by script to get dialog arguments.
  HRESULT GetDialogArguments([out, retval] BSTR *args_string);

  // Called by script inside the dialog to close and send back result.
  HRESULT CloseDialog([in] const BSTR result_string);

  // Called by script to check if we are in Pocket IE or Desktop IE
  HRESULT IsPocketIE([out, retval] VARIANT_BOOL *retval);
};
