var localized_strings = {
  "el": {
    "string-denied": "Δεν επιτρέπονται",
    "string-apply-accesskey": "A",
    "string-remove": "Κατάργηση",
    "string-gears-settings": "Ρυθμίσεις Gears",
    "string-apply": "Εφαρμογή",
    "string-cancel-accesskey": "C",
    "string-cancel": "Άκυρο",
    "string-html-title": "Ρυθμίσεις Gears",
    "string-allowed": "Επιτρέπονται",
    "string-local-storage": "Τοπικός αποθηκευτικός χώρος",
    "string-nosites": "Δεν υπάρχουν ιστότοποι.",
    "string-permissions-description": "Ο παρακάτω πίνακας δείχνει τα δικαιώματα που χορηγήσατε σε κάθε ιστότοπο που επιχείρησε να χρησιμοποιήσει το Gears.",
    "string-location-data": "Τοποθεσία",
    "string-version": "Έκδοση Gears 0.4.20.0"
  },
  "gu": {
    "string-denied": "નકારેલું",
    "string-apply-accesskey": "A",
    "string-remove": "દૂર કરો",
    "string-gears-settings": "Gears સેટિંગ્સ",
    "string-apply": "લાગુ કરો",
    "string-cancel-accesskey": "C",
    "string-cancel": "રદ કરો",
    "string-html-title": "Gears સેટિંગ્સ",
    "string-allowed": "મંજુર કરેલ",
    "string-local-storage": "સ્થાનિક સ્ટોરેજ",
    "string-nosites": "કોઇ સાઇટ્સ નથીં.",
    "string-permissions-description": "નીચેનુ કોષ્ટક દર્શાવે છે કે તમે જુદી-જુદી સાઇટ્સને કઇ પરવાનગીઓ આપેલી છે કે જેમણે Gearsનો ઉપયોગ કરવાનો પ્રયત્ન કર્યો છે.",
    "string-location-data": "સ્થાન",
    "string-version": "Gears સંસ્કરણ 0.4.20.0"
  },
  "zh-TW": {
    "string-denied": "遭拒",
    "string-apply-accesskey": "A",
    "string-remove": "移除",
    "string-gears-settings": "Gears 設定",
    "string-apply": "套用",
    "string-cancel-accesskey": "C",
    "string-cancel": "取消",
    "string-html-title": "Gears 設定",
    "string-allowed": "允許",
    "string-local-storage": "本機儲存",
    "string-nosites": "沒有網站。",
    "string-permissions-description": "下表顯示您授予嘗試使用 Gears 之各個網站的權限。",
    "string-location-data": "位置",
    "string-version": "Gears 版本 0.4.20.0"
  },
  "vi": {
    "string-denied": "Bị từ chối",
    "string-apply-accesskey": "P",
    "string-remove": "Xoá",
    "string-gears-settings": "Cài đặt Gears",
    "string-apply": "Áp dụng",
    "string-cancel-accesskey": "H",
    "string-cancel": "Huỷ",
    "string-html-title": "Cài đặt Gears",
    "string-allowed": "Được phép",
    "string-local-storage": "Bộ nhớ cục bộ",
    "string-nosites": "Không có trang web nào.",
    "string-permissions-description": "Bảng dưới đây hiển thị các quyền bạn cấp cho mỗi trang đã cố gắng sử dụng Gears.",
    "string-location-data": "Vị trí",
    "string-version": "Gears phiên bản 0.4.20.0"
  },
  "ca": {
    "string-denied": "Denegat",
    "string-apply-accesskey": "P",
    "string-remove": "Elimina",
    "string-gears-settings": "Configuració de Gears",
    "string-apply": "Aplica",
    "string-cancel-accesskey": "C",
    "string-cancel": "Cancel·la",
    "string-html-title": "Configuració de Gears",
    "string-allowed": "Permès",
    "string-local-storage": "Emmagatzematge local",
    "string-nosites": "Cap lloc.",
    "string-permissions-description": "La taula següent mostra els permisos que teniu a cada lloc que ha intentat utilizar Gears.",
    "string-location-data": "Ubicació",
    "string-version": "Versió de Gears 0.4.20.0"
  },
  "it": {
    "string-denied": "Non consentito",
    "string-apply-accesskey": "A",
    "string-remove": "Rimuovi",
    "string-gears-settings": "Impostazioni di Appcelerator Titanium",
    "string-apply": "Applica",
    "string-cancel-accesskey": "A",
    "string-cancel": "Annulla",
    "string-html-title": "Impostazioni di Appcelerator Titanium",
    "string-allowed": "Consentito",
    "string-local-storage": "Archiviazione locale",
    "string-nosites": "Nessun sito.",
    "string-permissions-description": "La tabella riportata di seguito mostra le autorizzazioni concesse ai siti che hanno tentato di utilizzare Appcelerator Titanium.",
    "string-location-data": "Posizione",
    "string-version": "Versione di Appcelerator Titanium 0.4.20.0"
  },
  "kn": {
    "string-denied": "ನಿರಾಕರಿಸಲಾಗಿದೆ",
    "string-apply-accesskey": "A",
    "string-remove": "ತೆಗೆಯಿರಿ",
    "string-gears-settings": "Gears ಸೆಟ್ಟಿಂಗ್ಸ್",
    "string-apply": "ಅನ್ವಯಿಸಿ",
    "string-cancel-accesskey": "C",
    "string-cancel": "ರದ್ದುಮಾಡು",
    "string-html-title": "Gears ಸೆಟ್ಟಿಂಗ್ಸ್",
    "string-allowed": "ಅನುಮತಿಸಲಾಗಿದೆ",
    "string-local-storage": "ಸ್ಥಳೀಯ ಶೇಖರಣೆ",
    "string-nosites": "ಸೈಟುಗಳಿಲ್ಲ.",
    "string-permissions-description": "ಕೆಳಗಿನ ಟೇಬಲ್ Gears ಬಳಸಲು ಪ್ರಯತ್ನಿಸಿದ ಪ್ರತಿಯೊಂದು ಸೈಟ್ ಗೂ ನೀವು ನೀಡಿದ ಅನುಮತಿಗಳನ್ನು ತೋರಿಸುತ್ತಿದೆ.",
    "string-location-data": "ಸ್ಥಳ",
    "string-version": "0.4.20.0 Gears ಆವೃತ್ತಿ"
  },
  "ar": {
    "string-denied": "مرفوض",
    "string-apply-accesskey": "س",
    "string-remove": "إزالة",
    "string-gears-settings": "إعدادات Gears",
    "string-apply": "تطبيق",
    "string-cancel-accesskey": "غ",
    "string-cancel": "إلغاء",
    "string-html-title": "إعدادات Gears",
    "string-allowed": "مسموح",
    "string-local-storage": "تخزين محلي",
    "string-nosites": "لا توجد مواقع.",
    "string-permissions-description": "يوضح الجدول أدناه الأذونات التي قمت بمنحها لكل موقع حاول استخدام Gears.",
    "string-location-data": "الموقع",
    "string-version": "Gears الإصدار 0.4.20.0"
  },
  "ml": {
    "string-denied": "തടഞ്ഞു",
    "string-apply-accesskey": "A",
    "string-remove": "നീക്കംചെയ്യൂ",
    "string-gears-settings": "Gears ക്രമീകരണങ്ങള്",
    "string-apply": "അപേക്ഷിക്കുക",
    "string-cancel-accesskey": "C",
    "string-cancel": "റദ്ദാക്കൂ",
    "string-html-title": "Gears ക്രമീകരണങ്ങള്",
    "string-allowed": "അനുവദിച്ചു",
    "string-local-storage": "പ്രാദേശിക ശേഖരം",
    "string-nosites": "സൈറ്റുകളൊന്നുമില്ല.",
    "string-permissions-description": "താഴെക്കാണുന്ന പട്ടിക Gears ഉപയോഗിക്കാന് ശ്രമിച്ച ഓരോ സൈറ്റിലേക്കും അനുവദിച്ചവ കാണിക്കുന്നു.",
    "string-location-data": "ലൊക്കേഷന്",
    "string-version": "Gears പതിപ്പ് 0.4.20.0"
  },
  "cs": {
    "string-denied": "Zamítnuto",
    "string-apply-accesskey": "P",
    "string-remove": "Odebrat",
    "string-gears-settings": "Nastavení aplikace Gears",
    "string-apply": "Použít",
    "string-cancel-accesskey": "R",
    "string-cancel": "Zrušit",
    "string-html-title": "Nastavení aplikace Gears",
    "string-allowed": "Povoleno",
    "string-local-storage": "Místní úložiště",
    "string-nosites": "Žádné weby.",
    "string-permissions-description": "Následující tabulka zobrazuje oprávnění udělená každému webu, který se pokusil použít aplikaci Gears.",
    "string-location-data": "Lokalita",
    "string-version": "Gears verze 0.4.20.0"
  },
  "et": {
    "string-denied": "Keelatud",
    "string-apply-accesskey": "L",
    "string-remove": "Eemalda",
    "string-gears-settings": "Gearsi seaded",
    "string-apply": "Rakenda",
    "string-cancel-accesskey": "T",
    "string-cancel": "Tühista",
    "string-html-title": "Gearsi seaded",
    "string-allowed": "Lubatud",
    "string-local-storage": "Kohalik salvestamine",
    "string-nosites": "Saidid puuduvad.",
    "string-permissions-description": "Alljärgnev tabel näitab lubasid, mille olete igale Gearsi kasutada püüdnud saidile andnud.",
    "string-location-data": "Asukoht",
    "string-version": "Gearsi versioon 0.4.20.0"
  },
  "id": {
    "string-denied": "Ditolak",
    "string-apply-accesskey": "A",
    "string-remove": "Hapus",
    "string-gears-settings": "Pengaturan Gears",
    "string-apply": "Terapkan",
    "string-cancel-accesskey": "C",
    "string-cancel": "Batalkan",
    "string-html-title": "Pengaturan Gears",
    "string-allowed": "Diizinkan",
    "string-local-storage": "Penyimpanan lokal",
    "string-nosites": "Tiada situs.",
    "string-permissions-description": "Tabel berikut menunjukkan izin yang telah Anda berikan ke setiap situs yang berusaha menggunakan Gears.",
    "string-location-data": "Lokasi",
    "string-version": "Versi Gears 0.4.20.0"
  },
  "es": {
    "string-denied": "Denegado",
    "string-apply-accesskey": "P",
    "string-remove": "Quitar",
    "string-gears-settings": "Configuración Gears",
    "string-apply": "Aplicar",
    "string-cancel-accesskey": "C",
    "string-cancel": "Cancelar",
    "string-html-title": "Configuración Gears",
    "string-allowed": "Permitido",
    "string-local-storage": "Almacenamiento local",
    "string-nosites": "No hay sitios.",
    "string-permissions-description": "La siguiente tabla muestra las autorizaciones que has concedido a cada sitio en el que has intentado usar Gears.",
    "string-location-data": "Ubicación",
    "string-version": "Versión Gears 0.4.20.0"
  },
  "en-GB": {
    "string-denied": "Denied",
    "string-apply-accesskey": "A",
    "string-remove": "Remove",
    "string-gears-settings": "Gears Settings",
    "string-apply": "Apply",
    "string-cancel-accesskey": "C",
    "string-cancel": "Cancel",
    "string-html-title": "Gears Settings",
    "string-allowed": "Allowed",
    "string-local-storage": "Local storage",
    "string-nosites": "No sites.",
    "string-permissions-description": "The table below shows the permissions you have granted to each site that has attempted to use Gears.",
    "string-location-data": "Location",
    "string-version": "Gears version 0.4.20.0"
  },
  "ru": {
    "string-denied": "Отказано",
    "string-apply-accesskey": "A",
    "string-remove": "Удалить",
    "string-gears-settings": "Настройки Gears",
    "string-apply": "Применить",
    "string-cancel-accesskey": "C",
    "string-cancel": "Отмена",
    "string-html-title": "Настройки Gears",
    "string-allowed": "Разрешено",
    "string-local-storage": "Локальное хранилище",
    "string-nosites": "Нет сайтов.",
    "string-permissions-description": "В таблице ниже перечислены разрешения, предоставленные каждому сайту, который пытался воспользоваться Gears.",
    "string-location-data": "Местонахождение",
    "string-version": "Gears версии 0.4.20.0"
  },
  "nl": {
    "string-denied": "Geweigerd",
    "string-apply-accesskey": "A",
    "string-remove": "Verwijderen",
    "string-gears-settings": "Instellingen voor Gears",
    "string-apply": "Toepassen",
    "string-cancel-accesskey": "C",
    "string-cancel": "Annuleren",
    "string-html-title": "Instellingen voor Gears",
    "string-allowed": "Toegestaan",
    "string-local-storage": "Lokale opslag",
    "string-nosites": "Geen sites.",
    "string-permissions-description": "Voor elke site die heeft geprobeerd Gears te gebruiken, worden in de tabel hieronder de machtigingen weergegeven die u aan deze site hebt verleend.",
    "string-location-data": "Locatie",
    "string-version": "Gears-versie 0.4.20.0"
  },
  "no": {
    "string-denied": "Ikke tillatt",
    "string-apply-accesskey": "T",
    "string-remove": "Fjern",
    "string-gears-settings": "Innstillinger for Gears",
    "string-apply": "Bruk",
    "string-cancel-accesskey": "A",
    "string-cancel": "Avbryt",
    "string-html-title": "Innstillinger for Gears",
    "string-allowed": "Tillatt",
    "string-local-storage": "Lokal lagring",
    "string-nosites": "Ingen steder.",
    "string-permissions-description": "Tabellen nedenfor viser tillatelsene du har gitt til hvert nettsted som har forsøkt å bruke Gears.",
    "string-location-data": "Område",
    "string-version": "Gears versjon 0.4.20.0"
  },
  "tr": {
    "string-denied": "Reddedildi",
    "string-apply-accesskey": "V",
    "string-remove": "Kaldır",
    "string-gears-settings": "Gears Ayarları",
    "string-apply": "Uygula",
    "string-cancel-accesskey": "a",
    "string-cancel": "İptal",
    "string-html-title": "Gears Ayarları",
    "string-allowed": "İzin verildi",
    "string-local-storage": "Yerel depolama",
    "string-nosites": "Site yok.",
    "string-permissions-description": "Aşağıdaki tablo Gears kullanan her site için sağladığınız izinleri gösterir.",
    "string-location-data": "Konum",
    "string-version": "Gears sürüm 0.4.20.0"
  },
  "lv": {
    "string-denied": "Neatļauts",
    "string-apply-accesskey": "A",
    "string-remove": "Noņemt",
    "string-gears-settings": "Gears iestatījumi",
    "string-apply": "Lietot",
    "string-cancel-accesskey": "C",
    "string-cancel": "Atcelt",
    "string-html-title": "Gears iestatījumi",
    "string-allowed": "Atļauts",
    "string-local-storage": "Vietējā atmiņa",
    "string-nosites": "Nav vietņu.",
    "string-permissions-description": "Tālāk minētā tabula rāda atļaujas, kuras esat piešķīris katrai vietnei, kas mēģināja lietot Gears.",
    "string-location-data": "Atrašanās vieta",
    "string-version": "Gears versija 0.4.20.0"
  },
  "lt": {
    "string-denied": "Neleidžiama",
    "string-apply-accesskey": "A",
    "string-remove": "Pašalinti",
    "string-gears-settings": "„Gears“ nuostatos",
    "string-apply": "Taikyti",
    "string-cancel-accesskey": "C",
    "string-cancel": "Atšaukti",
    "string-html-title": "„Gears“ nuostatos",
    "string-allowed": "Leidžiama",
    "string-local-storage": "Vietinė saugykla",
    "string-nosites": "Nėra svetainių.",
    "string-permissions-description": "Žemiau pateikta lentelėje rodomi leidimai, kuriuos suteikėte kiekvienai svetainei, bandžiusiai naudoti „Gears“.",
    "string-location-data": "Vietovė",
    "string-version": "„Gears“ versija 0.4.20.0"
  },
  "th": {
    "string-denied": "ปฏิเสธ",
    "string-apply-accesskey": "อ",
    "string-remove": "ลบ",
    "string-gears-settings": "การตั้งค่า Gears",
    "string-apply": "ใช้",
    "string-cancel-accesskey": "ย",
    "string-cancel": "ยกเลิก",
    "string-html-title": "การตั้งค่า Gears",
    "string-allowed": "อนุญาต",
    "string-local-storage": "พื้นที่เก็บข้อมูลในเครื่อง",
    "string-nosites": "ไม่มีไซต์",
    "string-permissions-description": "ตารางต่อไปนี้แสดงสิทธิ์ที่คุณให้แก่แต่ละไซต์ที่พยายามใช้ Gears",
    "string-location-data": "ตำแหน่ง",
    "string-version": "Gears เวอร์ชัน 0.4.20.0"
  },
  "ro": {
    "string-denied": "Refuzat",
    "string-apply-accesskey": "P",
    "string-remove": "Eliminaţi",
    "string-gears-settings": "Setări Gears",
    "string-apply": "Aplicaţi",
    "string-cancel-accesskey": "A",
    "string-cancel": "Anulaţi",
    "string-html-title": "Setări Gears",
    "string-allowed": "Permis",
    "string-local-storage": "Stocare locală",
    "string-nosites": "Niciun site.",
    "string-permissions-description": "Tabelul de mai jos afişează permisiunile pe care le-aţi acordat fiecărui site care a încercat să utilizeze Gears.",
    "string-location-data": "Locaţie",
    "string-version": "Versiune Gears 0.4.20.0"
  },
  "is": {
    "string-denied": "Hafnað",
    "string-apply-accesskey": "L",
    "string-remove": "Fjarlægja",
    "string-gears-settings": "Stillingar Gears",
    "string-apply": "Nota",
    "string-cancel-accesskey": "H",
    "string-cancel": "Hætta við",
    "string-html-title": "Stillingar Gears",
    "string-allowed": "Leyft",
    "string-local-storage": "Staðbundin geymsla",
    "string-nosites": "Engin vefsvæði.",
    "string-permissions-description": "Taflan hér fyrir neðan sýnir þær heimildir sem þú hefur veitt hverju svæði sem hefur reynt að nota Gears.",
    "string-location-data": "Staðsetning",
    "string-version": "Gears útgáfa 0.4.20.0"
  },
  "fil": {
    "string-denied": "Tinganggihan",
    "string-apply-accesskey": "P",
    "string-remove": "Alisin",
    "string-gears-settings": "Mga Setting ng Gear",
    "string-apply": "Ilapat",
    "string-cancel-accesskey": "I",
    "string-cancel": "Ikansela",
    "string-html-title": "Mga Setting ng Gear",
    "string-allowed": "Pinahintulutan",
    "string-local-storage": "Lokal na imbakan",
    "string-nosites": "Walang mga site.",
    "string-permissions-description": "Ang talahanayan sa ibaba ay nagpapakita ng mga pahintulot na naibigay mo sa bawat site na sinubukang gumamit ng Mga Gear.",
    "string-location-data": "Lokasyon",
    "string-version": "bersyon ng Mga Gear 0.4.20.0"
  },
  "ta": {
    "string-denied": "அனுமதி மறுத்தது",
    "string-apply-accesskey": "A",
    "string-remove": "அகற்று",
    "string-gears-settings": "Gears அமைப்புகள்",
    "string-apply": "பயன்படுத்து",
    "string-cancel-accesskey": "C",
    "string-cancel": "ரத்துசெய்",
    "string-html-title": "Gears அமைப்புகள்",
    "string-allowed": "அனுமதிக்கப்பட்டது",
    "string-local-storage": "உள்ளக சேமிப்பிடம்",
    "string-nosites": "தளங்கள் இல்லை.",
    "string-permissions-description": "கீழே உள்ள அட்டவணை Gears ஐப் பயன்படுத்த ஒவ்வொரு தளங்களுக்கும் நீங்கள் அளித்த அனுமதிகளை காட்டுகிறது.",
    "string-location-data": "இருப்பிடம்",
    "string-version": "Gears பதிப்பு 0.4.20.0"
  },
  "fr": {
    "string-denied": "Refusé",
    "string-apply-accesskey": "A",
    "string-remove": "Supprimer",
    "string-gears-settings": "Paramètres de Appcelerator Titanium",
    "string-apply": "Appliquer",
    "string-cancel-accesskey": "U",
    "string-cancel": "Annuler",
    "string-html-title": "Paramètres de Appcelerator Titanium",
    "string-allowed": "Autorisé",
    "string-local-storage": "Stockage local",
    "string-nosites": "Aucun site.",
    "string-permissions-description": "Le tableau ci-dessous montre les autorisations que vous avez accordées à chaque site ayant tenté d'utiliser Appcelerator Titanium.",
    "string-location-data": "Emplacement",
    "string-version": "Version 0.4.20.0 de Appcelerator Titanium"
  },
  "bg": {
    "string-denied": "Отказан",
    "string-apply-accesskey": "A",
    "string-remove": "Премахване",
    "string-gears-settings": "Настройки на Gears",
    "string-apply": "Прилагане",
    "string-cancel-accesskey": "С",
    "string-cancel": "Отказ",
    "string-html-title": "Настройки на Gears",
    "string-allowed": "Разрешен",
    "string-local-storage": "Локално хранилище",
    "string-nosites": "Няма сайтове.",
    "string-permissions-description": "В таблицата по-долу са показани дадените от вас разрешения на всеки сайт, който се е опитал да използва Gears.",
    "string-location-data": "Местоположение",
    "string-version": "Версия 0.4.20.0 на Gears"
  },
  "uk": {
    "string-denied": "Відхилено",
    "string-apply-accesskey": "A",
    "string-remove": "Видалити",
    "string-gears-settings": "Налаштування Gears",
    "string-apply": "Застосувати",
    "string-cancel-accesskey": "C",
    "string-cancel": "Скасувати",
    "string-html-title": "Налаштування Gears",
    "string-allowed": "Дозволено",
    "string-local-storage": "Збереження на локальному диску",
    "string-nosites": "Сайти відсутні.",
    "string-permissions-description": "У нижченаведеній таблиці наведено дозволи, надані кожному сайту, який намагається використовувати Gears.",
    "string-location-data": "Розташування",
    "string-version": "Gears версії 0.4.20.0"
  },
  "hr": {
    "string-denied": "Odbijeno",
    "string-apply-accesskey": "A",
    "string-remove": "Ukloni",
    "string-gears-settings": "Postavke Gearsa",
    "string-apply": "Primijeni",
    "string-cancel-accesskey": "C",
    "string-cancel": "Odustani",
    "string-html-title": "Postavke Gearsa",
    "string-allowed": "Dopušteno",
    "string-local-storage": "Lokalna pohrana",
    "string-nosites": "Nema web-lokacija.",
    "string-permissions-description": "U dolje navedenoj tablici navedene su dozvole koje ste dali svakoj web-lokaciji koja je pokušala koristiti Gears.",
    "string-location-data": "Lokacija",
    "string-version": "Verzija Gearsa 0.4.20.0"
  },
  "bn": {
    "string-denied": "অস্বীকৃত",
    "string-apply-accesskey": "A",
    "string-remove": "সরান",
    "string-gears-settings": "Gears সেটিংস",
    "string-apply": "প্রয়োগ",
    "string-cancel-accesskey": "C",
    "string-cancel": "বাতিল",
    "string-html-title": "Gears সেটিংস",
    "string-allowed": "অনুমতিপ্রাপ্ত",
    "string-local-storage": "স্থানিয় স্টোরেজ",
    "string-nosites": "কোন সাইটগুলি ׀",
    "string-permissions-description": "নিচের সারণিটির অনুসারে আপনি প্রত্যেকটি সাইটটিকে অনুমতি দিয়েছেন যা Gears ব্যবহার করতে চেয়েছে ׀",
    "string-location-data": "অবস্থান",
    "string-version": "Gears সংস্করণ 0.4.20.0"
  },
  "en-US": {
    "string-denied": "Denied",
    "string-apply-accesskey": "A",
    "string-remove": "Remove",
    "string-gears-settings": "Gears Settings",
    "string-apply": "Apply",
    "string-cancel-accesskey": "C",
    "string-cancel": "Cancel",
    "string-html-title": "Gears Settings",
    "string-allowed": "Allowed",
    "string-local-storage": "Local storage",
    "string-nosites": "No sites.",
    "string-permissions-description": "The table below shows the permissions you have granted to each site that has attempted to use Gears.",
    "string-location-data": "Location",
    "string-version": "Gears version 0.4.20.0"
  },
  "da": {
    "string-denied": "Afvist",
    "string-apply-accesskey": "I",
    "string-remove": "Fjern",
    "string-gears-settings": "Indstillinger til Gears",
    "string-apply": "Anvend",
    "string-cancel-accesskey": "A",
    "string-cancel": "Annuller",
    "string-html-title": "Indstillinger til Gears",
    "string-allowed": "Tilladt",
    "string-local-storage": "Lokalt lager",
    "string-nosites": "Ingen websteder.",
    "string-permissions-description": "Nedenstående tabel indeholder en oversigt over de tilladelser, du har givet til de websteder, der har forsøgt at få adgang til at bruge Gears.",
    "string-location-data": "Placering",
    "string-version": "Gears-version PRODUKT_VERSION"
  },
  "fa": {
    "string-denied": "مردود",
    "string-apply-accesskey": "مجاز",
    "string-remove": "حذف",
    "string-gears-settings": "تنظیمات Gears",
    "string-apply": "اعمال",
    "string-cancel-accesskey": "C",
    "string-cancel": "لغو",
    "string-html-title": "تنظیمات Gears",
    "string-allowed": "مجاز",
    "string-local-storage": "مکان ذخیره",
    "string-nosites": "سایتی وجود ندارد.",
    "string-permissions-description": "جدول زیر مجوزهای شما برای دستیابی به سایتهایی که از Gears استفاده می کند را نشان می دهد.",
    "string-location-data": "موقعیت",
    "string-version": "Gears نسخه 0.4.20.0"
  },
  "hi": {
    "string-denied": "अस्वीकृत",
    "string-apply-accesskey": "अनुमति दें",
    "string-remove": "निकालें",
    "string-gears-settings": "Gears सेटिंग्स",
    "string-apply": "लागू करें",
    "string-cancel-accesskey": "रद्द करें",
    "string-cancel": "रद्द करें",
    "string-html-title": "Gears सेटिंग्स",
    "string-allowed": "स्वीकार्य",
    "string-local-storage": "स्थानीय संग्रहण",
    "string-nosites": "कोई साइट नहीं.",
    "string-permissions-description": "नीचे दी गई टेबल वे अनुमतियाँ दिखाती है जो आपने उन साइटों को दी है जिन्होंने Gears का उपयोग करने का प्रयास किया है.",
    "string-location-data": "स्थिति",
    "string-version": "Gears संस्करण 0.4.20.0"
  },
  "pt-BR": {
    "string-denied": "Negado",
    "string-apply-accesskey": "P",
    "string-remove": "Remover",
    "string-gears-settings": "Configurações do Gears",
    "string-apply": "Aplicar",
    "string-cancel-accesskey": "C",
    "string-cancel": "Cancelar",
    "string-html-title": "Configurações do Gears",
    "string-allowed": "Permitido",
    "string-local-storage": "Armazenamento local",
    "string-nosites": "Nenhum site.",
    "string-permissions-description": "A tabela abaixo mostra as permissões concedidas por você a cada site que tentou usar o Gears.",
    "string-location-data": "Local",
    "string-version": "Gears versão 0.4.20.0"
  },
  "fi": {
    "string-denied": "Estetty",
    "string-apply-accesskey": "A",
    "string-remove": "Poista",
    "string-gears-settings": "Gearsin asetukset",
    "string-apply": "Ota käyttöön",
    "string-cancel-accesskey": "P",
    "string-cancel": "Peruuta",
    "string-html-title": "Gearsin asetukset",
    "string-allowed": "Sallittu",
    "string-local-storage": "Paikallinen tallennus",
    "string-nosites": "Ei sivustoja.",
    "string-permissions-description": "Oheisesta taulukosta näet luvat, jotka olet myöntänyt jokaiselle sivustolle, joka on yrittänyt käyttää Gearsia.",
    "string-location-data": "Sijainti",
    "string-version": "Gearsin versio 0.4.20.0"
  },
  "hu": {
    "string-denied": "Megtagadva",
    "string-apply-accesskey": "E",
    "string-remove": "Eltávolítás",
    "string-gears-settings": "A Szinkron beállításai",
    "string-apply": "OK",
    "string-cancel-accesskey": "M",
    "string-cancel": "Mégse",
    "string-html-title": "A Szinkron beállításai",
    "string-allowed": "Engedélyezve",
    "string-local-storage": "Helyi tárolás",
    "string-nosites": "Nincsenek webhelyek.",
    "string-permissions-description": "Az alábbi táblázat azt mutatja, hogy a Szinkron használatát megkísérlő webhelyeknek milyen engedélyeket adott.",
    "string-location-data": "Hely",
    "string-version": "A Szinkron verziószáma: 0.4.20.0"
  },
  "ja": {
    "string-denied": "拒否",
    "string-apply-accesskey": "A",
    "string-remove": "削除",
    "string-gears-settings": "Gears の設定",
    "string-apply": "適用",
    "string-cancel-accesskey": "C",
    "string-cancel": "キャンセル",
    "string-html-title": "Gears の設定",
    "string-allowed": "許可",
    "string-local-storage": "ローカル保存",
    "string-nosites": "サイトがありません。",
    "string-permissions-description": "下記の表は、Gears を使用しようとした各サイトに与えた権限を示しています。",
    "string-location-data": "場所",
    "string-version": "Gears バージョン 0.4.20.0"
  },
  "he": {
    "string-denied": "נדחה",
    "string-apply-accesskey": "א",
    "string-remove": "הסר",
    "string-gears-settings": "הגדרות Gears",
    "string-apply": "החל",
    "string-cancel-accesskey": "ביטול",
    "string-cancel": "ביטול",
    "string-html-title": "הגדרות Gears",
    "string-allowed": "מותר",
    "string-local-storage": "אחסון מקומי",
    "string-nosites": "ללא אתרים.",
    "string-permissions-description": "הטבלה שלהלן מראה את ההרשאות שהענקת לכל אתר שניסה להשתמש ב-Gears.",
    "string-location-data": "מיקום",
    "string-version": "Gears בגרסה 0.4.20.0"
  },
  "te": {
    "string-denied": "అనుమతి లేని",
    "string-apply-accesskey": "A",
    "string-remove": "తొలగించు",
    "string-gears-settings": "Gears సెట్టింగులు",
    "string-apply": "వర్తించు",
    "string-cancel-accesskey": "C",
    "string-cancel": "రద్దు చెయ్యి",
    "string-html-title": "Gears సెట్టింగులు",
    "string-allowed": "అనుమతించబడిన",
    "string-local-storage": "స్థానిక నిల్వ",
    "string-nosites": "సైట్లు లేవు.",
    "string-permissions-description": "ఈ క్రింది పట్టిక, మీరు ఏ సైట్లకి Gears ఉపయోగించడానికి అనుమతి ఇచ్చారో, చూపిస్తుంది.",
    "string-location-data": "స్థానం",
    "string-version": "0.4.20.0 Gears వర్షన్"
  },
  "pt-PT": {
    "string-denied": "Negado",
    "string-apply-accesskey": "P",
    "string-remove": "Remover",
    "string-gears-settings": "Definições do Gears",
    "string-apply": "Aplicar",
    "string-cancel-accesskey": "C",
    "string-cancel": "Cancelar",
    "string-html-title": "Definições do Gears",
    "string-allowed": "Permitido",
    "string-local-storage": "Armazenamento local",
    "string-nosites": "Não existem sites.",
    "string-permissions-description": "A tabela abaixo mostra as autorizações que concedeu a cada site que tentou utilizar o Gears.",
    "string-location-data": "Localização",
    "string-version": "Versão 0.4.20.0 do Gears"
  },
  "sr": {
    "string-denied": "Забрањен приступ",
    "string-apply-accesskey": "M",
    "string-remove": "Уклони",
    "string-gears-settings": "Gears подешавања",
    "string-apply": "Примени",
    "string-cancel-accesskey": "О",
    "string-cancel": "Откажи",
    "string-html-title": "Gears подешавања",
    "string-allowed": "Дозвољен приступ",
    "string-local-storage": "Локални простор за складиштење",
    "string-nosites": "Ниједан сајт.",
    "string-permissions-description": "Табела испод приказује дозволе које сте одобрили сваком сајту који је покушао да користи Gears.",
    "string-location-data": "Локација",
    "string-version": "Gears верзија 0.4.20.0"
  },
  "ko": {
    "string-denied": "거부됨",
    "string-apply-accesskey": "A",
    "string-remove": "삭제",
    "string-gears-settings": "Gears 설정",
    "string-apply": "적용",
    "string-cancel-accesskey": "C",
    "string-cancel": "취소",
    "string-html-title": "Gears 설정",
    "string-allowed": "허용",
    "string-local-storage": "로컬 저장소",
    "string-nosites": "사이트가 없습니다.",
    "string-permissions-description": "다음 표는 Gears를 사용하려 시도했던 각 사이트에 대해 승인받은 사용권한을 보여줍니다.",
    "string-location-data": "위치",
    "string-version": "Gears 버전 0.4.20.0"
  },
  "sv": {
    "string-denied": "Nekad",
    "string-apply-accesskey": "T",
    "string-remove": "Ta bort",
    "string-gears-settings": "Inställningar i Gears",
    "string-apply": "Tillämpa",
    "string-cancel-accesskey": "A",
    "string-cancel": "Avbryt",
    "string-html-title": "Inställningar i Gears",
    "string-allowed": "Tillåten",
    "string-local-storage": "Lokal lagring",
    "string-nosites": "Inga webbplatser",
    "string-permissions-description": "Tabellen nedan visar beviljade tillstånd för varje webbplats som har försökt att använda Gears.",
    "string-location-data": "Plats",
    "string-version": "Gears version 0.4.20.0"
  },
  "ur": {
    "string-denied": "مسترد",
    "string-apply-accesskey": "A",
    "string-remove": "حذف کریں",
    "string-gears-settings": "گیئرز کی ترتیبات",
    "string-apply": "اطلاق کریں",
    "string-cancel-accesskey": "C",
    "string-cancel": "منسوخ",
    "string-html-title": "گیئرز کی ترتیبات",
    "string-allowed": "اجازت ہے",
    "string-local-storage": "ذخیرہ کرنے کی مقامی جگہ",
    "string-nosites": "کوئی سائٹ نہیں۔",
    "string-permissions-description": "ذیل کا جدول ان اجازتوں کو دکھاتا ہے جو آپ نے ان سائٹوں کیلئے دی ہیں جنہوں نے گیئرز کے استعمال کی کوشش کی تھی۔",
    "string-location-data": "جائے وقوع",
    "string-version": "گیئرز ورژن0.4.20.0"
  },
  "sk": {
    "string-denied": "Odmietnuté",
    "string-apply-accesskey": "P",
    "string-remove": "Odstrániť",
    "string-gears-settings": "Nastavenia rozšírenia Gears",
    "string-apply": "Použiť",
    "string-cancel-accesskey": "R",
    "string-cancel": "Zrušiť",
    "string-html-title": "Nastavenia rozšírenia Gears",
    "string-allowed": "Povolené",
    "string-local-storage": "Lokálny ukladací priestor",
    "string-nosites": "Žiadne lokality.",
    "string-permissions-description": "V nižšie uvedenej tabuľke sú uvedené povolenia, ktoré máte udelené pre všetky lokality, ktoré sa pokúsili použiť rozšírenie Gears.",
    "string-location-data": "Umiestnenie",
    "string-version": "Gears, verzia 0.4.20.0"
  },
  "zh-CN": {
    "string-denied": "已拒绝",
    "string-apply-accesskey": "A",
    "string-remove": "删除",
    "string-gears-settings": "Gears 设置",
    "string-apply": "应用",
    "string-cancel-accesskey": "C",
    "string-cancel": "取消",
    "string-html-title": "Gears 设置",
    "string-allowed": "允许",
    "string-local-storage": "本地存储",
    "string-nosites": "没有网站。",
    "string-permissions-description": "下表显示了您向试图使用 Gears 的每个网站授予了哪些权限。",
    "string-location-data": "位置",
    "string-version": "Gears 版本 0.4.20.0"
  },
  "de": {
    "string-denied": "Verweigert",
    "string-apply-accesskey": "Z",
    "string-remove": "Entfernen",
    "string-gears-settings": "Gears-Einstellungen",
    "string-apply": "Anwenden",
    "string-cancel-accesskey": "A",
    "string-cancel": "Abbrechen",
    "string-html-title": "Gears-Einstellungen",
    "string-allowed": "Zulässig",
    "string-local-storage": "Lokaler Speicherplatz",
    "string-nosites": "Keine Sites.",
    "string-permissions-description": "Die untenstehende Tabelle zeigt die Berechtigungen an, die Sie jeder Site gewährt haben, die versucht hat, Gears zu verwenden.",
    "string-location-data": "Speicherort",
    "string-version": "Gears-Version PRODUKT_VERSION"
  },
  "pl": {
    "string-denied": "Zabroniono",
    "string-apply-accesskey": "Z",
    "string-remove": "Usuń",
    "string-gears-settings": "Ustawienia wtyczki Gears",
    "string-apply": "Zastosuj",
    "string-cancel-accesskey": "A",
    "string-cancel": "Anuluj",
    "string-html-title": "Ustawienia wtyczki Gears",
    "string-allowed": "Zezwolono",
    "string-local-storage": "Przechowywanie danych lokalnie",
    "string-nosites": "Brak witryn.",
    "string-permissions-description": "Poniższa tabela zawiera uprawnienia, jakie przyznano każdej z witryn próbujących użyć wtyczki Gears.",
    "string-location-data": "Lokalizacja",
    "string-version": "Gears 0.4.20.0"
  },
  "ms": {
    "string-denied": "Ditolak",
    "string-apply-accesskey": "N",
    "string-remove": "Keluarkan",
    "string-gears-settings": "Tetapan Gear",
    "string-apply": "Gunakan",
    "string-cancel-accesskey": "B",
    "string-cancel": "Batal",
    "string-html-title": "Tetapan Gear",
    "string-allowed": "Dibenarkan",
    "string-local-storage": "Penyimpanan setempat",
    "string-nosites": "Tiada tapak.",
    "string-permissions-description": "Jadual di bawah menunjukkan kebenaran yang telah anda berikan kepada setiap tapak yang telah cuba menggunakan Gear.",
    "string-location-data": "Lokasi",
    "string-version": "Versi Gear 0.4.20.0"
  },
  "sl": {
    "string-denied": "Zavrnjeno",
    "string-apply-accesskey": "A",
    "string-remove": "Odstrani",
    "string-gears-settings": "Nastavitve programa Gears",
    "string-apply": "Uporabi",
    "string-cancel-accesskey": "C",
    "string-cancel": "Prekliči",
    "string-html-title": "Nastavitve programa Gears",
    "string-allowed": "Dovoljeno",
    "string-local-storage": "Lokalna shramba",
    "string-nosites": "Ni spletnih mest.",
    "string-permissions-description": "V spodnji tabeli so prikazana dovoljenja, ki ste jih podelili vsem spletnim mestom, ki so poskusila uporabljati program Gears.",
    "string-location-data": "Lokacija",
    "string-version": "Različica programa Gears 0.4.20.0"
  },
  "mr": {
    "string-denied": "अननुमत",
    "string-apply-accesskey": "A",
    "string-remove": "काढा",
    "string-gears-settings": "Gears सेटिंग्ज",
    "string-apply": "लागू करा",
    "string-cancel-accesskey": "C",
    "string-cancel": "रद्द करा",
    "string-html-title": "Gears सेटिंग्ज",
    "string-allowed": "अनुमत",
    "string-local-storage": "स्थानिक संचय",
    "string-nosites": "साइट नाहीत.",
    "string-permissions-description": "निम्न सारणी Gears वापरण्याचा प्रयत्न केलेल्या प्रत्येक साइटकरिता आपल्याकडे किती परवानग्या आहेत हे दर्शविते.",
    "string-location-data": "स्थान",
    "string-version": "Gears आवृत्ती 0.4.20.0"
  },
  "or": {
    "string-denied": "ମନାକରନ୍ତୁ",
    "string-apply-accesskey": "A",
    "string-remove": "ଅପସାରଣ",
    "string-gears-settings": "Gears ସେଟିଂସମୂହ",
    "string-apply": "ଲାଗୁ କରନ୍ତୁ",
    "string-cancel-accesskey": "C",
    "string-cancel": "ବାତିଲ୍",
    "string-html-title": "Gears ସେଟିଂସମୂହ",
    "string-allowed": "ଅନୁମତି ପ୍ରାପ୍ତ କରନ୍ତୁ",
    "string-local-storage": "ସ୍ଥାନୀୟ ସଂଞ୍ଚୟ",
    "string-nosites": "କୌଣସି ସାଇଟମାନ ନାହିଁ |",
    "string-permissions-description": "ନିମ୍ନ ସାରଣୀ ଆପଣ ପ୍ରତ୍ୟେକ ସାଇଟକୁ ପ୍ରଦାନ କରିଥିବା ସ୍ବୀକୃତି ଦର୍ଶାଉଛି,ଯାହା Gears ବ୍ୟବହାର କରିବାକୁ ପଦକ୍ଷେପ ନେଇଛି |",
    "string-location-data": "ସ୍ଥାନ",
    "string-version": "Gears ସଂସ୍କରଣ 0.4.20.0"
  }
};

// Insert all localized strings for the specified locale into the div or span
// matching the id.
function loadI18nStrings(locale) {
  var rtl_languages = ['he', 'ar', 'fa', 'ur'];

  if (!locale) {
    locale = 'en-US';
  } else {
    if (!localized_strings[locale]) {
      // For xx-YY locales, determine what the base locale is.
      var base_locale = locale.split('-')[0];

      if (localized_strings[base_locale]) {
        locale = base_locale;
      } else {
        locale = 'en-US';
      }
    }
  }

  var strings = localized_strings[locale];

  // If the specified locale is an right to left language, change the direction
  // of the page.
  for (index in rtl_languages) {
    if (locale == rtl_languages[index]) {
      document.body.dir = "rtl";
      break;
    }
  }

  // Copy each string to the proper UI element, if it exists.
  for (name in strings) {
    if (name == 'string-html-title') {
      if (!browser.ie_mobile) {
        // IE Mobile dialogs don't have a title bar.
        // Furthermore, document.title is undefined in IE Mobile on WinMo 5.
        // It's also impossible to add properties to the window object.
        // (see http://code.google.com/apis/gears/mobile.html)
        document.title = strings[name];
      }
    } else {
      var element = dom.getElementById(name);
      if (element) {
        element.innerHTML = strings[name];
      }
    }
  }
}

