var localized_strings = {
  "el": {
    "string-no": "Όχι",
    "string-header-desktop": "Αυτός ο ιστότοπος θέλει να δημιουργήσει μια συντόμευση στον υπολογιστή σας. Θέλετε να το επιτρέψετε αυτό;",
    "string-no-accesskey": "Ο",
    "string-header-wince": "Αυτός ο ιστότοπος θέλει να δημιουργήσει μια συντόμευση στη λίστα προγραμμάτων. Θέλετε να το επιτρέψετε;",
    "string-title-simple": "Δημιουργία συντομεύσεων εφαρμογών",
    "string-ok-accesskey": "O",
    "string-ok": "OK",
    "string-cancel-accesskey": "C",
    "string-cancel": "Άκυρο",
    "string-startmenu": "Μενού έναρξης",
    "string-yes": "Ναι",
    "string-never-allow": "Να μην επιτρέπεται ποτέ αυτή η συντόμευση",
    "string-yes-accesskey": "Ν",
    "string-quicklaunch": "Γραμμή γρήγορης εκκίνησης",
    "string-never-allow-wince": "Να μην επιτρέπεται ποτέ",
    "string-desktop": "Επιφάνεια εργασίας",
    "string-title-default": "Gears - Δημιουργία συντόμευσης στην επιφάνεια εργασίας",
    "string-location-query": "Δημιουργία συντομεύσεων στις παρακάτω θέσεις:"
  },
  "gu": {
    "string-no": "નહીં",
    "string-header-desktop": "આ વેબસાઇટને તમારા કમ્પ્યુટર પર એક શોર્ટકટ બનાવવો છે શું આની તમારે મંજુરી આપવી છે?",
    "string-no-accesskey": "N",
    "string-header-wince": "આ વેબસાઇટ આપની પ્રોગ્રામોની સૂચિમાં શૉર્ટકટ્સ બનાવવા માંગે છે. શું આપ આને મંજુરી આપવા માંગો છો?",
    "string-title-simple": "એપ્લિકેશન શોર્ટકટ બનાવો",
    "string-ok-accesskey": "O",
    "string-ok": "ઓકે",
    "string-cancel-accesskey": "C",
    "string-cancel": "રદ કરો",
    "string-startmenu": "પ્રારંભ મેનુ",
    "string-yes": "હા",
    "string-never-allow": "આ શૉર્ટકટને ક્યારેય મંજૂર કરશો નહીં",
    "string-yes-accesskey": "Y",
    "string-quicklaunch": "ક્વિક લોંચ બાર",
    "string-never-allow-wince": "ક્યારેય મંજૂર કરશો નહીં",
    "string-desktop": "ડેસ્કટોપ",
    "string-title-default": "Gears - ડેસ્ક્ટોપ શોર્ટકટ બનાવો",
    "string-location-query": "નીચેના સ્થાનો પર શોર્ટકટ્સ બનાવો"
  },
  "zh-TW": {
    "string-no": "否",
    "string-header-desktop": "這個網站要在您的電腦上建立捷徑。 您是否允許這個動作？",
    "string-no-accesskey": "N",
    "string-header-wince": "這個網站要在您的程式清單中建立捷徑。 您是否允許這個動作？",
    "string-title-simple": "建立應用程式捷徑",
    "string-ok-accesskey": "O",
    "string-ok": "確定",
    "string-cancel-accesskey": "C",
    "string-cancel": "取消",
    "string-startmenu": "開始功能表",
    "string-yes": "是",
    "string-never-allow": "永不允許這個捷徑",
    "string-yes-accesskey": "Y",
    "string-quicklaunch": "快速啟動列",
    "string-never-allow-wince": "永不允許",
    "string-desktop": "桌面",
    "string-title-default": "Gears - 建立桌面捷徑",
    "string-location-query": "在下列位置建立捷徑："
  },
  "vi": {
    "string-no": "Không",
    "string-header-desktop": "Trang web này muốn tạo một lối tắt trên màn hình của bạn. Bạn có cho phép tác vụ này không?",
    "string-no-accesskey": "K",
    "string-header-wince": "Trang web này muốn tạo lối tắt trong danh sách chương trình của bạn. Bạn có cho phép tác vụ này không?",
    "string-title-simple": "Tạp Lối tắt cho Ứng dụng",
    "string-ok-accesskey": "O",
    "string-ok": "OK",
    "string-cancel-accesskey": "H",
    "string-cancel": "Huỷ",
    "string-startmenu": "Trình đơn bắt đầu",
    "string-yes": "Có",
    "string-never-allow": "Không bao giờ cho phép lối tắt này",
    "string-yes-accesskey": "C",
    "string-quicklaunch": "Thanh khởi động nhanh",
    "string-never-allow-wince": "Không bao giờ cho phép",
    "string-desktop": "Màn hình",
    "string-title-default": "Gears - Tạo Lối tắt trên Màn hình",
    "string-location-query": "Tạo lối tắt trong các vị trí sau:"
  },
  "ca": {
    "string-no": "No",
    "string-header-desktop": "Aquest lloc web vol crear una drecera al vostre ordinador. Ho voleu permetre?",
    "string-no-accesskey": "N",
    "string-header-wince": "Aquest lloc web vol crear una drecera a la vostra llista de programes. Ho voleu permetre?",
    "string-title-simple": "Creeu dreceres d'aplicacions",
    "string-ok-accesskey": "O",
    "string-ok": "D'acord",
    "string-cancel-accesskey": "C",
    "string-cancel": "Cancel·la",
    "string-startmenu": "Menú Inici",
    "string-yes": "Sí",
    "string-never-allow": "No permetre mai aquesta drecera",
    "string-yes-accesskey": "S",
    "string-quicklaunch": "Barra d'inici ràpid",
    "string-never-allow-wince": "No permetre mai",
    "string-desktop": "Escriptori",
    "string-title-default": "Gears - Crea una drecera a l'escriptori",
    "string-location-query": "Crea dreceres a les ubicacions següents:"
  },
  "it": {
    "string-no": "No",
    "string-header-desktop": "Questo sito web vuole creare un collegamento sul tuo computer. Consentire l'operazione?",
    "string-no-accesskey": "N",
    "string-header-wince": "Questo sito Web vuole creare sul tuo desktop un collegamento nel tuo elenco di programmi. Consentire l'operazione?",
    "string-title-simple": "Crea collegamenti applicazione",
    "string-ok-accesskey": "O",
    "string-ok": "OK",
    "string-cancel-accesskey": "A",
    "string-cancel": "Annulla",
    "string-startmenu": "Menu Start",
    "string-yes": "Sì",
    "string-never-allow": "Non consentire mai questo collegamento",
    "string-yes-accesskey": "S",
    "string-quicklaunch": "Barra Avvio veloce",
    "string-never-allow-wince": "Non consentire mai",
    "string-desktop": "Desktop",
    "string-title-default": "Appcelerator Titanium - Crea collegamento sul desktop",
    "string-location-query": "Crea collegamenti nelle seguenti posizioni:"
  },
  "kn": {
    "string-no": "ಇಲ್ಲ",
    "string-header-desktop": "ಈ ವೆಬ್ ಸೈಟ್ ನಿಮ್ಮ ಕಂಪ್ಯೂಟರಿನಲ್ಲಿ ಒಂದು ಶಾರ್ಟ್ ಕಟ್ ರಚಿಸಲು ಬಯಸುತ್ತದೆ. ಇದನ್ನು ನೀವು ಅನುಮತಿಸಲು ಬಯಸುತ್ತೀರಾ?",
    "string-no-accesskey": "N",
    "string-header-wince": "ನಿಮ್ಮ ಕಾರ್ಯಕ್ರಮಗಳ ಪಟ್ಟಿಯಲ್ಲಿ ಶಾರ್ಟ್‌ಕಟ್‌ಗಳನ್ನು ರಚಿಸಲು ಈ ವೆಬ್‌ಸೈಟ್ ಬಯಸುತ್ತದೆ. ನೀವು ಇದನ್ನು ಅನುಮತಿಸಲು ಬಯಸುತ್ತೀರಾ?",
    "string-title-simple": "ಅಪ್ಲಿಕೇಶನ್ ಶಾರ್ಟ್ ಕಟ್ ಗಳನ್ನು ರಚಿಸಿ",
    "string-ok-accesskey": "O",
    "string-ok": "ಸರಿ",
    "string-cancel-accesskey": "C",
    "string-cancel": "ರದ್ದುಮಾಡು",
    "string-startmenu": "ಪ್ರಾರಂಭ ಮೆನು",
    "string-yes": "ಹೌದು",
    "string-never-allow": "ಈ ಶಾರ್ಟ್‌ಕಟ್‌ನ್ನು ಎಂದಿಗೂ ಅನುಮತಿಸಬೇಡಿ",
    "string-yes-accesskey": "Y",
    "string-quicklaunch": "ಕ್ವಿಕ್ ಲಾಂಚ್ ಬಾರ್",
    "string-never-allow-wince": "ಎಂದಿಗೂ ಅನುಮತಿಸಬೇಡಿ",
    "string-desktop": "ಡೆಸ್ಕ್ ಟಾಪ್",
    "string-title-default": "Gears - ಡೆಸ್ಕ್ ಟಾಪ್ ಶಾರ್ಟ್ ಕಟ್ ರಚಿಸಿ",
    "string-location-query": "ಈ ಕೆಳಗಿನ ಸ್ಥಳಗಳಲ್ಲಿ ಶಾರ್ಟ್ ಕಟ್ ಗಳನ್ನು ರಚಿಸಿ:"
  },
  "ar": {
    "string-no": "لا",
    "string-header-desktop": "يتطلب موقع الويب هذا إنشاء اختصار على الكمبيوتر الخاص بك. هل تريد السماح بذلك؟",
    "string-no-accesskey": "ل",
    "string-header-wince": "يرغب موقع الويب هذا في إنشاء اختصار في قائمة البرامج لديك. هل ترغب في السماح له بذلك؟",
    "string-title-simple": "إنشاء اختصارات للتطبيقات",
    "string-ok-accesskey": "م",
    "string-ok": "موافق",
    "string-cancel-accesskey": "غ",
    "string-cancel": "إلغاء",
    "string-startmenu": "القائمة ابدأ",
    "string-yes": "نعم",
    "string-never-allow": "عدم السماح بهذا الاختصار مطلقًا",
    "string-yes-accesskey": "ن",
    "string-quicklaunch": "شريط التشغيل السريع",
    "string-never-allow-wince": "عدم السماح مطلقًا",
    "string-desktop": "سطح المكتب",
    "string-title-default": "Gears - إنشاء اختصار لسطح المكتب",
    "string-location-query": "قم بإنشاء اختصارات في المواقع التالية:"
  },
  "ml": {
    "string-no": "ഇല്ല",
    "string-header-desktop": "ഈ വെബ്സൈറ്റ് നിങ്ങളുടെ കമ്പ്യൂട്ടരില് ഒരു കുറുക്കുവഴി സൃഷ്ടിക്കാന് ആവശ്യപ്പെടുന്നു. ഇതനുവദിക്കാന് നിങ്ങള് ആഗ്രഹിക്കുന്നുണ്ടോ?",
    "string-no-accesskey": "N",
    "string-header-wince": "പ്രോഗ്രാമുകളുടെ പട്ടികയില്‍ ഒരു കുറുക്കുവഴി സൃഷ്ടിക്കാന്‍ ഈ വെബ്സൈറ്റ് ആവശ്യപ്പെടുന്നു. ഇതനുവദിക്കാന്‍ നിങ്ങള്‍ ആഗ്രഹിക്കുന്നുണ്ടോ?",
    "string-title-simple": "അപ്ലിക്കേഷന്‍ കുറുക്കുവഴികള്‍ സൃഷ്ടിക്കുക",
    "string-ok-accesskey": "O",
    "string-ok": "ശരി",
    "string-cancel-accesskey": "C",
    "string-cancel": "റദ്ദാക്കൂ",
    "string-startmenu": "തുടങ്ങുക മെനു",
    "string-yes": "അതെ",
    "string-never-allow": "ഈ കുറുക്കുവഴി ഒരിക്കലും അനുവദിക്കരുത്",
    "string-yes-accesskey": "Y",
    "string-quicklaunch": "ദ്രുത ലോഞ്ച് ബാര്‍",
    "string-never-allow-wince": "ഒരിക്കലും അനുവദിക്കരുത്",
    "string-desktop": "ഡെസ്ക്ടോപ്",
    "string-title-default": "Gears - ഡെസ്ക്ടോപ് കുറുക്കുവഴി സൃഷ്ടിക്കുക",
    "string-location-query": "താഴെക്കാണുന്ന ലോക്കഷനുകളില് കുറുക്കുവഴികള് സൃഷ്ടിക്കുക"
  },
  "cs": {
    "string-no": "Ne",
    "string-header-desktop": "Tato webová stránka chce vytvořit zástupce ve vašem počítači. Chcete tuto akci povolit?",
    "string-no-accesskey": "N",
    "string-header-wince": "Tento web chce vytvořit zástupce v seznamu programů. Chcete tuto akci povolit?",
    "string-title-simple": "Vytvořit zástupce aplikace",
    "string-ok-accesskey": "O",
    "string-ok": "OK",
    "string-cancel-accesskey": "R",
    "string-cancel": "Zrušit",
    "string-startmenu": "Nabídka Start",
    "string-yes": "Ano",
    "string-never-allow": "Nikdy nepovolit tohoto zástupce",
    "string-yes-accesskey": "A",
    "string-quicklaunch": "Panel rychlého spuštění",
    "string-never-allow-wince": "Nikdy nepovolit",
    "string-desktop": "Plocha",
    "string-title-default": "Gears – vytvořit zástupce na ploše",
    "string-location-query": "Vytvořit zástupce v následujících umístěních:"
  },
  "et": {
    "string-no": "Ei",
    "string-header-desktop": "See veebilehekülg tahab teie arvutisse otseteed luua. Kas soovite seda lubada?",
    "string-no-accesskey": "E",
    "string-header-wince": "Veebisait soovib teie programmiloendisse luua otsetee. Kas lubate seda?",
    "string-title-simple": "Loo rakenduse otseteed",
    "string-ok-accesskey": "O",
    "string-ok": "OK",
    "string-cancel-accesskey": "T",
    "string-cancel": "Tühista",
    "string-startmenu": "Start-menüü",
    "string-yes": "Jah",
    "string-never-allow": "Ära luba seda otseteed kunagi",
    "string-yes-accesskey": "J",
    "string-quicklaunch": "Kiirkäivitusriba",
    "string-never-allow-wince": "Ära luba kunagi",
    "string-desktop": "Töölaud",
    "string-title-default": "Gears – loo töölaua otsetee",
    "string-location-query": "Loo otseteed järgmistesse asukohtadesse:"
  },
  "id": {
    "string-no": "Tidak",
    "string-header-desktop": "Website ini ingin membuat pintasan pada komputer Anda. Anda ingin mengizinkannya?",
    "string-no-accesskey": "T",
    "string-header-wince": "Situs web ini ingin membuat pintasan dalam daftar program Anda. Apakah Anda mengizinkannya?",
    "string-title-simple": "Buat Pintasan Aplikasi",
    "string-ok-accesskey": "O",
    "string-ok": "OK",
    "string-cancel-accesskey": "C",
    "string-cancel": "Batalkan",
    "string-startmenu": "Menu Mulai",
    "string-yes": "Ya",
    "string-never-allow": "Jangan pernah mengizinkan pintasan ini",
    "string-yes-accesskey": "Y",
    "string-quicklaunch": "Bilah luncur cepat",
    "string-never-allow-wince": "Jangan pernah mengizinkan",
    "string-desktop": "Desktop",
    "string-title-default": "Gears - Buat Jalan Pintas Desktop",
    "string-location-query": "Buat pintasan di lokasi berikut ini:"
  },
  "es": {
    "string-no": "No",
    "string-header-desktop": "Este sitio web desea crear un acceso directo en tu equipo. ¿Quieres permitirlo?",
    "string-no-accesskey": "N",
    "string-header-wince": "Este sitio web desea crear un acceso directo en tu lista de programas. ¿Quieres permitirlo?",
    "string-title-simple": "Crear accesos directos de la aplicación",
    "string-ok-accesskey": "A",
    "string-ok": "Aceptar",
    "string-cancel-accesskey": "C",
    "string-cancel": "Cancelar",
    "string-startmenu": "Menú Inicio",
    "string-yes": "Sí",
    "string-never-allow": "No permitir nunca este acceso directo",
    "string-yes-accesskey": "S",
    "string-quicklaunch": "Barra de inicio rápida",
    "string-never-allow-wince": "No permitir nunca",
    "string-desktop": "Escritorio",
    "string-title-default": "Gears - Crear acceso directo en el escritorio",
    "string-location-query": "Crear accesos directos en las siguientes ubicaciones:"
  },
  "en-GB": {
    "string-no": "No",
    "string-header-desktop": "This website wants to create a shortcut on your computer. Do you want to allow this?",
    "string-no-accesskey": "N",
    "string-header-wince": "This website wants to create the shortcuts listed below in your list of programmes. Do you want to allow this?",
    "string-title-simple": "Create Application Shortcuts",
    "string-ok-accesskey": "O",
    "string-ok": "OK",
    "string-cancel-accesskey": "C",
    "string-cancel": "Cancel",
    "string-startmenu": "Start menu",
    "string-yes": "Yes",
    "string-never-allow": "Never allow this shortcut",
    "string-yes-accesskey": "Y",
    "string-quicklaunch": "Quick launch bar",
    "string-never-allow-wince": "Never allow",
    "string-desktop": "Desktop",
    "string-title-default": "Gears - Create Desktop Shortcut",
    "string-location-query": "Create shortcuts in the following locations:"
  },
  "ru": {
    "string-no": "Нет",
    "string-header-desktop": "Этот веб-сайт собирается создать ярлык на вашем компьютере. Разрешить?",
    "string-no-accesskey": "N",
    "string-header-wince": "Этот веб-сайт пытается создать ярлык в вашем списке программ. Разрешить?",
    "string-title-simple": "Создать ярлыки для приложений",
    "string-ok-accesskey": "O",
    "string-ok": "ОК",
    "string-cancel-accesskey": "C",
    "string-cancel": "Отмена",
    "string-startmenu": "Меню \"Пуск\"",
    "string-yes": "Да",
    "string-never-allow": "Никогда не разрешать создание этого ярлыка",
    "string-yes-accesskey": "Y",
    "string-quicklaunch": "Панель быстрого запуска",
    "string-never-allow-wince": "Никогда",
    "string-desktop": "Рабочий стол",
    "string-title-default": "Gears — создать ярлык на рабочем столе",
    "string-location-query": "Создать ярлыки со следующим размещением:"
  },
  "nl": {
    "string-no": "Nee",
    "string-header-desktop": "Deze website wil een snelkoppeling maken op je computer. Vind je dat goed?",
    "string-no-accesskey": "N",
    "string-header-wince": "Deze website wil een snelkoppeling maken in uw programmalijst. Wilt u dit toestaan?",
    "string-title-simple": "Toepassingssnelkoppelingen maken",
    "string-ok-accesskey": "O",
    "string-ok": "OK",
    "string-cancel-accesskey": "C",
    "string-cancel": "Annuleren",
    "string-startmenu": "Startmenu",
    "string-yes": "Ja",
    "string-never-allow": "Deze snelkoppeling nooit toestaan",
    "string-yes-accesskey": "J",
    "string-quicklaunch": "Werkbalk Snel starten",
    "string-never-allow-wince": "Nooit toestaan",
    "string-desktop": "Bureaublad",
    "string-title-default": "Gears - Snelkoppeling op bureaublad maken",
    "string-location-query": "Snelkoppelingen maken op de volgende locaties:"
  },
  "no": {
    "string-no": "Nei",
    "string-header-desktop": "Dette nettstedet ønsker å opprette en snarvei på datamaskinen. Vil du tillate dette?",
    "string-no-accesskey": "N",
    "string-header-wince": "Dette nettstedet vil opprette en snarvei i listen over programmer. Vil du tillate dette?",
    "string-title-simple": "Opprett snarveier til programmer",
    "string-ok-accesskey": "O",
    "string-ok": "OK",
    "string-cancel-accesskey": "A",
    "string-cancel": "Avbryt",
    "string-startmenu": "Start-meny",
    "string-yes": "Ja",
    "string-never-allow": "Avvis alltid denne snarveien",
    "string-yes-accesskey": "J",
    "string-quicklaunch": "Hurtigstartlinje",
    "string-never-allow-wince": "Avvis alltid",
    "string-desktop": "Skrivebord",
    "string-title-default": "Gears – Opprett snarvei på skrivebordet",
    "string-location-query": "Opprett snarveier på følgende plasseringer:"
  },
  "tr": {
    "string-no": "Hayır",
    "string-header-desktop": "Bu web sitesi bilgisayarınızda bir kısayol oluşturmak istiyor. Buna izin vermek istiyor musunuz?",
    "string-no-accesskey": "H",
    "string-header-wince": "Bu web sitesi, programlar listenizde bir kısayol oluşturmak istiyor. Buna izin vermek istiyor musunuz?",
    "string-title-simple": "Uygulama Kısayolları Oluştur",
    "string-ok-accesskey": "T",
    "string-ok": "Tamam",
    "string-cancel-accesskey": "a",
    "string-cancel": "İptal",
    "string-startmenu": "Başlat menüsü",
    "string-yes": "Evet",
    "string-never-allow": "Bu kısayola asla izin verme",
    "string-yes-accesskey": "E",
    "string-quicklaunch": "Hızlı başlat çubuğu",
    "string-never-allow-wince": "Asla izin verme",
    "string-desktop": "Masaüstü",
    "string-title-default": "Gears - Masaüstü Kısayolu Oluştur",
    "string-location-query": "Kısayolları aşağıdaki konumlarda oluştur:"
  },
  "lv": {
    "string-no": "Nē",
    "string-header-desktop": "Šī vietne vēlas izveidot datorā saīsni. Vai vēlaties to atļaut?",
    "string-no-accesskey": "Nē",
    "string-header-wince": "Šī vietne jūsu programmu sarakstā gatavojas izveidot īsceļu. Vai atļausit?",
    "string-title-simple": "Izveidot lietojumprogrammu saīsnes",
    "string-ok-accesskey": "O",
    "string-ok": "Labi",
    "string-cancel-accesskey": "C",
    "string-cancel": "Atcelt",
    "string-startmenu": "Izvēlne Sākt",
    "string-yes": "Jā",
    "string-never-allow": "Nekad neatļaut šī īsceļa izveidi",
    "string-yes-accesskey": "Jā",
    "string-quicklaunch": "Ātrās palaišanas josla",
    "string-never-allow-wince": "Nekad neatļaut",
    "string-desktop": "Datora darbvirsma",
    "string-title-default": "Gears — darbvirsmas saīsnes izveide",
    "string-location-query": "Izveidot saīsnes šādās vietās:"
  },
  "lt": {
    "string-no": "Ne",
    "string-header-desktop": "Ši svetainė sukurs šaukinį jūsų kompiuteryje. Ar leisti?",
    "string-no-accesskey": "N",
    "string-header-wince": "Ši svetainė sukurs šaukinį programų sąraše. Ar leisti?",
    "string-title-simple": "Sukurti programos šaukinius",
    "string-ok-accesskey": "O",
    "string-ok": "Gerai",
    "string-cancel-accesskey": "C",
    "string-cancel": "Atšaukti",
    "string-startmenu": "Pradinis meniu",
    "string-yes": "Taip",
    "string-never-allow": "Niekada neleisti šio šaukinio",
    "string-yes-accesskey": "T",
    "string-quicklaunch": "Sparčiosios paleisties juosta",
    "string-never-allow-wince": "Niekada neleisti",
    "string-desktop": "Darbalaukis",
    "string-title-default": "„Gears“ – sukurti darbalaukio šaukinį",
    "string-location-query": "Sukurti šaukinius šiose vietose:"
  },
  "th": {
    "string-no": "ไม่",
    "string-header-desktop": "เว็บไซต์นี้ต้องการสร้างทางลัดบนเดสก์ท็อปของคุณ คุณต้องการอนุญาตหรือไม่",
    "string-no-accesskey": "ม",
    "string-header-wince": "เว็บไซต์นี้ต้องการสร้างทางลัดที่ปรากฏในรายการโปรแกรมของคุณ คุณต้องการอนุญาตหรือไม่",
    "string-title-simple": "สร้างทางลัดของแอปพลิเคชัน",
    "string-ok-accesskey": "ต",
    "string-ok": "ตกลง",
    "string-cancel-accesskey": "ย",
    "string-cancel": "ยกเลิก",
    "string-startmenu": "เมนู Start",
    "string-yes": "ใช่",
    "string-never-allow": "ไม่อนุญาตให้สร้างทางลัดนี้",
    "string-yes-accesskey": "ช",
    "string-quicklaunch": "แถบ Quick Launch",
    "string-never-allow-wince": "ไม่อนุญาต",
    "string-desktop": "เดสก์ท็อป",
    "string-title-default": "Gears - สร้างทางลัดบนเดสก์ท็อป",
    "string-location-query": "สร้างทางลัดในตำแหน่งต่อไปนี้:"
  },
  "ro": {
    "string-no": "Nu",
    "string-header-desktop": "Acest site Web doreşte să creeze o comandă rapidă pe computerul dvs. Permiteţi acest lucru?",
    "string-no-accesskey": "N",
    "string-header-wince": "Acest site Web doreşte să creeze o comandă rapidă în lista dvs. de programe. Permiteţi acest lucru?",
    "string-title-simple": "Creaţi comenzi rapide pentru aplicaţii",
    "string-ok-accesskey": "O",
    "string-ok": "OK",
    "string-cancel-accesskey": "A",
    "string-cancel": "Anulaţi",
    "string-startmenu": "Meniul Start",
    "string-yes": "Da",
    "string-never-allow": "Nu permiteţi niciodată această comandă rapidă",
    "string-yes-accesskey": "D",
    "string-quicklaunch": "Bara Lansare rapidă",
    "string-never-allow-wince": "Nu permiteţi niciodată",
    "string-desktop": "Desktop",
    "string-title-default": "Gears – Creaţi comandă rapidă de pe desktop",
    "string-location-query": "Creaţi comenzi rapide în următoarele locaţii:"
  },
  "is": {
    "string-no": "Nei",
    "string-header-desktop": "Þetta vefsvæði óskar eftir að búa til flýtivísun á tölvunni hjá þér. Viltu leyfa það?",
    "string-no-accesskey": "N",
    "string-header-wince": "Þetta vefsvæði óskar eftir að búa til flýtivísun í forritalistanum hjá þér. Viltu leyfa það?",
    "string-title-simple": "Útbúa flýtivísanir fyrir forrit",
    "string-ok-accesskey": "O",
    "string-ok": "Í lagi",
    "string-cancel-accesskey": "H",
    "string-cancel": "Hætta við",
    "string-startmenu": "Upphafsvalmynd",
    "string-yes": "Já",
    "string-never-allow": "Aldrei heimila þessa flýtivísun",
    "string-yes-accesskey": "J",
    "string-quicklaunch": "Stika fyrir flýtiræsingu",
    "string-never-allow-wince": "Leyfa aldrei",
    "string-desktop": "Skjáborð",
    "string-title-default": "Gears - Setja flýtivísun á skjáborð",
    "string-location-query": "Útbúa flýtivísanir á eftirfarandi staðsetningum:"
  },
  "fil": {
    "string-no": "Hindi",
    "string-header-desktop": "Nais ng website na ito na lumikha ng isang shortcut sa iyong computer. Nais mo bang payagan ito?",
    "string-no-accesskey": "H",
    "string-header-wince": "Nais ng website na ito na lumikha ng isang shortcut sa iyong listahan ng mga program. Nais mo ba itong payagan?",
    "string-title-simple": "Lumikha ng mga Shortcut ng Application",
    "string-ok-accesskey": "K",
    "string-ok": "OK",
    "string-cancel-accesskey": "I",
    "string-cancel": "Ikansela",
    "string-startmenu": "Start menu",
    "string-yes": "Oo",
    "string-never-allow": "Huwag kailanman payagan ang shortcut na ito",
    "string-yes-accesskey": "O",
    "string-quicklaunch": "Quick launch bar",
    "string-never-allow-wince": "Huwag kailanman papayagan",
    "string-desktop": "Desktop",
    "string-title-default": "Mga Gear - Lumikha ng Shortcut sa Desktop",
    "string-location-query": "Lumikha ng mga shortcut sa mga sumusunod na lokasyon:"
  },
  "ta": {
    "string-no": "இல்லை",
    "string-header-desktop": "இந்தத் தளம் உங்கள் கணினியில் குறுக்கு வழியை உருவாக்க விரும்புகிறது. நீங்கள் இதை அனுமதிக்க வேண்டுமா?",
    "string-no-accesskey": "N",
    "string-header-wince": "உங்கள் நிரல்களின் பட்டியலில் ஒரு குறுக்குவழியை உருவாக்க இந்த வலைத்தளம் முயற்சிக்கிறது. இதனை அனுமதிக்க விரும்புகிறீர்களா?",
    "string-title-simple": "அப்ளிகேஷன் குறுக்குவழியை உருவாக்கு",
    "string-ok-accesskey": "O",
    "string-ok": "சரி",
    "string-cancel-accesskey": "C",
    "string-cancel": "ரத்துசெய்",
    "string-startmenu": "ஸ்டார்ட் மெனு",
    "string-yes": "ஆம்",
    "string-never-allow": "இந்த குறுக்குவழியை எப்போதும் அனுமதிக்க வேண்டாம்",
    "string-yes-accesskey": "Y",
    "string-quicklaunch": "குவிக் லான்ச் பார்",
    "string-never-allow-wince": "எப்போதும் அனுமதிக்காதே",
    "string-desktop": "டெஸ்க்டாப்",
    "string-title-default": "Gears - டெஸ்க்டாப் குறுக்குவழியை உருவாக்கு",
    "string-location-query": "பின்வரும் இடத்தில் குறுக்கு வழியை உருவாக்கவும்:"
  },
  "fr": {
    "string-no": "Non",
    "string-header-desktop": "Autorisez-vous la création par ce site Web d'un raccourci sur votre ordinateur ?",
    "string-no-accesskey": "N",
    "string-header-wince": "Ce site Web souhaite créer un raccourci dans votre liste de programmes. Autorisez-vous cette opération ?",
    "string-title-simple": "Créer des raccourcis d'applications",
    "string-ok-accesskey": "K",
    "string-ok": "OK",
    "string-cancel-accesskey": "U",
    "string-cancel": "Annuler",
    "string-startmenu": "Menu Démarrer",
    "string-yes": "Oui",
    "string-never-allow": "Ne jamais autoriser ce raccourci",
    "string-yes-accesskey": "O",
    "string-quicklaunch": "Barre de lancement rapide",
    "string-never-allow-wince": "Ne jamais autoriser",
    "string-desktop": "Bureau",
    "string-title-default": "Appcelerator Titanium - Créer un raccourci sur le Bureau",
    "string-location-query": "Créer des raccourcis aux emplacements suivants :"
  },
  "bg": {
    "string-no": "Не",
    "string-header-desktop": "Прави се опит за създаване на пряк път към този уебсайт на компютъра ви. Разрешавате ли?",
    "string-no-accesskey": "N",
    "string-header-wince": "Този уебсайт иска да създаде пряк път в списъка ви с програми. Разрешавате ли?",
    "string-title-simple": "Създаване на преки пътища към приложението",
    "string-ok-accesskey": "О",
    "string-ok": "OK",
    "string-cancel-accesskey": "С",
    "string-cancel": "Отказ",
    "string-startmenu": "Меню „Старт“",
    "string-yes": "Да",
    "string-never-allow": "Създаването на този пряк път не се разрешава изобщо",
    "string-yes-accesskey": "Y",
    "string-quicklaunch": "Лента за бързо стартиране",
    "string-never-allow-wince": "Не се разрешава изобщо",
    "string-desktop": "Работен плот",
    "string-title-default": "Gears - Създаване на пряк път на работния плот",
    "string-location-query": "Преки пътища да бъдат създадени на следните места:"
  },
  "uk": {
    "string-no": "Ні",
    "string-header-desktop": "Цей веб-сайт хоче створити ярлик на Вашому комп’ютері. Дозволити?",
    "string-no-accesskey": "N",
    "string-header-wince": "Цей веб-сайт намагається створити ярлик у списку програм. Дозволити це?",
    "string-title-simple": "Створіть ярлики програм",
    "string-ok-accesskey": "O",
    "string-ok": "OK",
    "string-cancel-accesskey": "C",
    "string-cancel": "Скасувати",
    "string-startmenu": "Меню \"Пуск\"",
    "string-yes": "Так",
    "string-never-allow": "Ніколи не дозволяти створювати цей ярлик",
    "string-yes-accesskey": "Y",
    "string-quicklaunch": "Панель \"Швидкий запуск\"",
    "string-never-allow-wince": "Ніколи не дозволяти",
    "string-desktop": "Робочий стіл",
    "string-title-default": "Gears – Створення ярликів на робочому столі",
    "string-location-query": "Створіть ярлики у таких розташуваннях:"
  },
  "hr": {
    "string-no": "Ne",
    "string-header-desktop": "Ova web-lokacija želi stvoriti prečac na Vašem računalu. Dopuštate li taj postupak?",
    "string-no-accesskey": "N",
    "string-header-wince": "Ova web-lokacija želi stvoriti prečac na Vašem popisu programa. Dopuštate li taj postupak?",
    "string-title-simple": "Stvori prečace za aplikacije",
    "string-ok-accesskey": "K",
    "string-ok": "U redu",
    "string-cancel-accesskey": "C",
    "string-cancel": "Odustani",
    "string-startmenu": "Izbornik Start",
    "string-yes": "Da",
    "string-never-allow": "Nikad ne dopuštaj ovaj prečac",
    "string-yes-accesskey": "D",
    "string-quicklaunch": "Traka za brzo pokretanje",
    "string-never-allow-wince": "Ne dopuštaj",
    "string-desktop": "Radna površina",
    "string-title-default": "Gears – Napravi prečac na radnoj površini",
    "string-location-query": "Stvori prečace na sljedećim mjestima:"
  },
  "bn": {
    "string-no": "না",
    "string-header-desktop": "এই ওয়েবসাইটটা আপনার কম্পিউটারে একটি শর্টকার্ট তৈরি করতে চায় ׀ আপনি কি এটার অনুমতি দিতে চান?",
    "string-no-accesskey": "N",
    "string-header-wince": "এই ওয়েবসাইটটি আপনার প্রোগ্রামের তালিকাতে একটি শর্টকাট তৈরি করতে চায়৷ আপনি কি এটি মঞ্জুরি দিতে চান?",
    "string-title-simple": "অ্যাপ্লিকেশান শর্টকার্ট তৈরি করুন",
    "string-ok-accesskey": "O",
    "string-ok": "ওকে",
    "string-cancel-accesskey": "C",
    "string-cancel": "বাতিল",
    "string-startmenu": "সূচনা মেনু",
    "string-yes": "হ্যাঁ",
    "string-never-allow": "কখনই এই শর্টকাটটির মঞ্জুরি দেবেন না",
    "string-yes-accesskey": "Y",
    "string-quicklaunch": "দ্রুত লঞ্চ দণ্ড",
    "string-never-allow-wince": "কখনই মঞ্জুরি দেবেন না",
    "string-desktop": "ডেস্কটপ",
    "string-title-default": "Gears- ডেস্কটপ শর্টকাট তৈরি করুন",
    "string-location-query": "এই যায়গাগুলিতে জন্য শর্টকার্টগুলি তৈরি করুন:"
  },
  "en-US": {
    "string-no": "No",
    "string-header-desktop": "This website wants to create a shortcut on your computer. Do you want to allow this?",
    "string-no-accesskey": "N",
    "string-header-wince": "This website wants to create a shortcut in your list of programs. Do you want to allow this?",
    "string-title-simple": "Create Application Shortcuts",
    "string-ok-accesskey": "O",
    "string-ok": "OK",
    "string-cancel-accesskey": "C",
    "string-cancel": "Cancel",
    "string-startmenu": "Start menu",
    "string-yes": "Yes",
    "string-never-allow": "Never allow this shortcut",
    "string-yes-accesskey": "Y",
    "string-quicklaunch": "Quick launch bar",
    "string-never-allow-wince": "Never allow",
    "string-desktop": "Desktop",
    "string-title-default": "Gears - Create Desktop Shortcut",
    "string-location-query": "Create shortcuts in the following locations:"
  },
  "da": {
    "string-no": "Nej",
    "string-header-desktop": "Dette websted ønsker at oprette en genvej på din computer. Vil du tillade det?",
    "string-no-accesskey": "N",
    "string-header-wince": "Dette websted ønsker at oprette en genvej i din liste med programmer. Vil du tillade det?",
    "string-title-simple": "Opret genveje til programmer",
    "string-ok-accesskey": "O",
    "string-ok": "OK",
    "string-cancel-accesskey": "A",
    "string-cancel": "Annuller",
    "string-startmenu": "Startmenu",
    "string-yes": "Ja",
    "string-never-allow": "Tillad aldrig denne genvej",
    "string-yes-accesskey": "J",
    "string-quicklaunch": "Værktøjslinjen Hurtig start",
    "string-never-allow-wince": "Giv aldrig tilladelse",
    "string-desktop": "Skrivebord",
    "string-title-default": "Gears – opret genvej på skrivebordet",
    "string-location-query": "Opret genveje følgende steder:"
  },
  "fa": {
    "string-no": "خیر",
    "string-header-desktop": "این وب سایت می خواهد میانبری در رایانه شما ایجاد کند. آیا اجازه می دهید؟",
    "string-no-accesskey": "N",
    "string-header-wince": "این وب سایت می خواهد یك میانبر در ليست برنامه های شما ایجاد کند. آیا اجازه می دهید؟",
    "string-title-simple": "ايجاد ميانبرهای برنامه",
    "string-ok-accesskey": "O",
    "string-ok": "تأیید",
    "string-cancel-accesskey": "C",
    "string-cancel": "لغو",
    "string-startmenu": "منوی شروع",
    "string-yes": "بله",
    "string-never-allow": "هرگز اجازه ندهید این میانبر ایجاد شود.",
    "string-yes-accesskey": "Y",
    "string-quicklaunch": "ميله راه اندازی سريع",
    "string-never-allow-wince": "هرگز اجازه داده نشود",
    "string-desktop": "دسک تاپ",
    "string-title-default": "Gears- ایجاد میانبر در دسک تاپ",
    "string-location-query": "ایجاد میانبر در محل های زیر:"
  },
  "hi": {
    "string-no": "नहीं",
    "string-header-desktop": "यह वेबसाइट आपके कंप्यूटर पर एक शॉर्टकट बनाना चाहती है. क्या आप इसकी अनुमति देना चाहते हैं?",
    "string-no-accesskey": "नहीं",
    "string-header-wince": "यह वेबसाइट आपके प्रोग्रामों की सूची में शॉर्टकट बनाना चाहती है. क्या आप इसकी अनुमति देना चाहते हैं?",
    "string-title-simple": "अनुप्रयोग शार्टकट बनाएँ",
    "string-ok-accesskey": "ठीक",
    "string-ok": "ठीक",
    "string-cancel-accesskey": "रद्द करें",
    "string-cancel": "रद्द करें",
    "string-startmenu": "प्रारंभ मेनू",
    "string-yes": "हाँ",
    "string-never-allow": "इस शॉर्टकट को कभी अनुमति न दें",
    "string-yes-accesskey": "हाँ",
    "string-quicklaunch": "त्वरित लॉन्च पट्टिका",
    "string-never-allow-wince": "कभी अनुमति न दें",
    "string-desktop": "डेस्कटॉप",
    "string-title-default": "Gears - डेस्कटॉप शॉर्टकट बनाएँ",
    "string-location-query": "निम्न स्थानों पर शॉर्टकट बनाएँ:"
  },
  "pt-BR": {
    "string-no": "Não",
    "string-header-desktop": "Este site deseja criar um atalho no seu computador. Gostaria de permitir isso?",
    "string-no-accesskey": "N",
    "string-header-wince": "Este site deseja criar um atalho na sua lista de programas. Deseja permitir isso?",
    "string-title-simple": "Criar atalhos do aplicativo",
    "string-ok-accesskey": "O",
    "string-ok": "OK",
    "string-cancel-accesskey": "C",
    "string-cancel": "Cancelar",
    "string-startmenu": "Menu Iniciar",
    "string-yes": "Sim",
    "string-never-allow": "Nunca permitir este atalho",
    "string-yes-accesskey": "Y",
    "string-quicklaunch": "Barra de inicialização rápida",
    "string-never-allow-wince": "Nunca permitir",
    "string-desktop": "Área de trabalho",
    "string-title-default": "Gears - Criar atalho na área de trabalho",
    "string-location-query": "Criar atalhos nos seguintes locais:"
  },
  "fi": {
    "string-no": "Ei",
    "string-header-desktop": "Tämä sivusto haluaa luoda pikakuvakkeen tietokoneellesi. Sallitko pikakuvakkeen luomisen?",
    "string-no-accesskey": "E",
    "string-header-wince": "Tämä sivusto haluaa luoda pikakuvakkeen ohjelmaluetteloosi. Sallitko pikakuvakkeen luomisen?",
    "string-title-simple": "Luo sovelluksista pikakuvakkeita",
    "string-ok-accesskey": "O",
    "string-ok": "OK",
    "string-cancel-accesskey": "P",
    "string-cancel": "Peruuta",
    "string-startmenu": "Aloitusvalikko",
    "string-yes": "Kyllä",
    "string-never-allow": "Älä koskaan salli tätä pikakuvaketta",
    "string-yes-accesskey": "K",
    "string-quicklaunch": "Pikakäynnistyspalkki",
    "string-never-allow-wince": "Älä koskaan salli",
    "string-desktop": "Työpöytä",
    "string-title-default": "Gears - Luo pikakuvake työpöydälle",
    "string-location-query": "Luo pikakuvakkeet seuraaviin kohteisiin:"
  },
  "hu": {
    "string-no": "Nem",
    "string-header-desktop": "Ez a webhely parancsikont szeretne létrehozni a számítógépen. Engedélyezi ezt?",
    "string-no-accesskey": "N",
    "string-header-wince": "Ez a webhely egy parancsikont kíván létrehozni a programlistában. Engedélyezi ezt?",
    "string-title-simple": "Alkalmazásindító parancsikonok létrehozása",
    "string-ok-accesskey": "O",
    "string-ok": "OK",
    "string-cancel-accesskey": "M",
    "string-cancel": "Mégse",
    "string-startmenu": "Start menü",
    "string-yes": "Igen",
    "string-never-allow": "Soha ne engedélyezze ezt a parancsikont",
    "string-yes-accesskey": "I",
    "string-quicklaunch": "Gyorsindítás eszköztár",
    "string-never-allow-wince": "Soha ne engedélyezze",
    "string-desktop": "Asztal",
    "string-title-default": "Szinkron - Asztali parancsikon létrehozása",
    "string-location-query": "Parancsikonok létrehozása a következő helyeken:"
  },
  "ja": {
    "string-no": "いいえ",
    "string-header-desktop": "デスクトップにこのサイトのショートカットが作成されます。許可しますか？",
    "string-no-accesskey": "N",
    "string-header-wince": "プログラム一覧にこのサイトのショートカットが作成されます。許可しますか？",
    "string-title-simple": "アプリケーション ショートカットを作成",
    "string-ok-accesskey": "O",
    "string-ok": "OK",
    "string-cancel-accesskey": "C",
    "string-cancel": "キャンセル",
    "string-startmenu": "スタート メニュー",
    "string-yes": "はい",
    "string-never-allow": "このショートカットを常に拒否する",
    "string-yes-accesskey": "Y",
    "string-quicklaunch": "クイック起動バー",
    "string-never-allow-wince": "許可しない",
    "string-desktop": "デスクトップ",
    "string-title-default": "Gears - デスクトップ ショートカットを作成",
    "string-location-query": "ショートカットを作成する場所"
  },
  "he": {
    "string-no": "לא",
    "string-header-desktop": "אתר אינטרנט זה רוצה ליצור קיצור דרך במחשב שלך. האם ברצונך לאפשר זאת?",
    "string-no-accesskey": "לא",
    "string-header-wince": "אתר אינטרנט זה מעוניין ליצור קיצור דרך ברשימת התוכניות שלך. האם ברצונך לאפשר זאת?",
    "string-title-simple": "צור קיצורי דרך ליישומים",
    "string-ok-accesskey": "אישור",
    "string-ok": "אישור",
    "string-cancel-accesskey": "ביטול",
    "string-cancel": "ביטול",
    "string-startmenu": "תפריט 'התחל'",
    "string-yes": "כן",
    "string-never-allow": "לעולם אל תאפשר קיצור דרך זה",
    "string-yes-accesskey": "כן",
    "string-quicklaunch": "סרגל הפעלה מהירה",
    "string-never-allow-wince": "לעולם אל תאפשר",
    "string-desktop": "שולחן עבודה",
    "string-title-default": "Gears - צור קיצור דרך בשולחן העבודה",
    "string-location-query": "צור קיצורי דרך במיקומים הבאים:"
  },
  "te": {
    "string-no": "వద్దు",
    "string-header-desktop": "ఈ వెబ్ సైట్ మీ కమ్ప్యుటర్ పైన షార్ట్ కట్స్ సృష్టించాలని అనుకుంటుంది . ఇది మీరు కొనసాగించాలని అనుకుంటున్నారా?",
    "string-no-accesskey": "N",
    "string-header-wince": "ఈ వెబ్‌సైట్ మీ ప్రోగ్రామ్‌ల జాబితాలో ఒక సత్వర మార్గాన్ని సృష్టించదలిచింది. మీరు దీనిని అనుమతించదలిచారా?",
    "string-title-simple": "అప్ప్లికేషన్ల షార్ట్కట్లు సృష్టించు",
    "string-ok-accesskey": "O",
    "string-ok": "OK",
    "string-cancel-accesskey": "C",
    "string-cancel": "రద్దు చెయ్యి",
    "string-startmenu": "స్టార్ట్ మెన్యు",
    "string-yes": "అవును",
    "string-never-allow": "ఈ సత్వర మార్గాన్ని ఎప్పుడూ అనుమతించవద్దు",
    "string-yes-accesskey": "Y",
    "string-quicklaunch": "శీఘ్ర లాంచ్ బార్",
    "string-never-allow-wince": "ఎప్పుడూ అనుమతించవద్దు",
    "string-desktop": "డెస్క్ టాప్",
    "string-title-default": "Gears -డెస్క్ టాప్ షార్ట్ కట్ని సృష్టించు",
    "string-location-query": "ఈ లోకేషన్స్ లో షార్ట్ కట్స్ సృష్టించండి:"
  },
  "pt-PT": {
    "string-no": "Não",
    "string-header-desktop": "Este Web site pretende criar um atalho no seu computador. Pretende permitir esta acção?",
    "string-no-accesskey": "N",
    "string-header-wince": "Este Web site pretende criar um atalho na sua lista de programas. Pretende permitir esta acção?",
    "string-title-simple": "Criar atalhos para as aplicações",
    "string-ok-accesskey": "O",
    "string-ok": "OK",
    "string-cancel-accesskey": "C",
    "string-cancel": "Cancelar",
    "string-startmenu": "Menu Iniciar",
    "string-yes": "Sim",
    "string-never-allow": "Nunca permitir este atalho",
    "string-yes-accesskey": "S",
    "string-quicklaunch": "Barra de iniciação rápida",
    "string-never-allow-wince": "Nunca permitir",
    "string-desktop": "Ambiente de trabalho",
    "string-title-default": "Gears - Criar atalho no ambiente de trabalho",
    "string-location-query": "Criar atalhos nas seguintes localizações:"
  },
  "sr": {
    "string-no": "Не",
    "string-header-desktop": "Овај веб сајт жели да направи пречицу на вашем рачунару. Да ли желите да то дозволите?",
    "string-no-accesskey": "N",
    "string-header-wince": "Овај веб сајт жели да направи пречицу на листи програма. Да ли желите да то дозволите?",
    "string-title-simple": "Креирај пречице апликација",
    "string-ok-accesskey": "P",
    "string-ok": "Потврди",
    "string-cancel-accesskey": "О",
    "string-cancel": "Откажи",
    "string-startmenu": "Старт мени",
    "string-yes": "Да",
    "string-never-allow": "Никада не дозволи ову пречицу",
    "string-yes-accesskey": "D",
    "string-quicklaunch": "Трака за брзо покретање",
    "string-never-allow-wince": "Никада не дозволи",
    "string-desktop": "Радна површина",
    "string-title-default": "Gears - направи пречицу на радној површини",
    "string-location-query": "Hаправи пречице на следећим локацијама:"
  },
  "ko": {
    "string-no": "아니요",
    "string-header-desktop": "웹사이트에서 사용자 컴퓨터에 바로가기를 만들려고 합니다. 허용하시겠습니까?",
    "string-no-accesskey": "N",
    "string-header-wince": "웹사이트에서 프로그램 목록에 바로가기를 만들려고 합니다. 바로가기를 만드시겠습니까?",
    "string-title-simple": "애플리케이션 바로가기 만들기",
    "string-ok-accesskey": "O",
    "string-ok": "확인",
    "string-cancel-accesskey": "C",
    "string-cancel": "취소",
    "string-startmenu": "시작 메뉴",
    "string-yes": "예",
    "string-never-allow": "바로가기를 허용하지 않음",
    "string-yes-accesskey": "Y",
    "string-quicklaunch": "빠른실행 표시줄",
    "string-never-allow-wince": "허용 안함",
    "string-desktop": "바탕화면",
    "string-title-default": "Gears - 바탕화면 바로가기 만들기",
    "string-location-query": "바로가기 생성 위치:"
  },
  "sv": {
    "string-no": "Nej",
    "string-header-desktop": "Webbplatsen försöker skapa en genväg i datorn. Vill du tillåta det?",
    "string-no-accesskey": "N",
    "string-header-wince": "Den här webbplatsen vill skapa en genväg i din programlista. Vill du tillåta det?",
    "string-title-simple": "Skapa programgenvägar",
    "string-ok-accesskey": "O",
    "string-ok": "OK",
    "string-cancel-accesskey": "A",
    "string-cancel": "Avbryt",
    "string-startmenu": "Start-meny",
    "string-yes": "Ja",
    "string-never-allow": "Tillåt aldrig den här genvägen",
    "string-yes-accesskey": "J",
    "string-quicklaunch": "Fältet Snabbstart",
    "string-never-allow-wince": "Tillåt aldrig",
    "string-desktop": "Skrivbord",
    "string-title-default": "Gears - Skapa genväg på skrivbordet",
    "string-location-query": "Skapa genvägar på följande platser:"
  },
  "ur": {
    "string-no": "نہیں",
    "string-header-desktop": "یہ ویب سائٹ آپ کے کمپیوٹر پر ایک شارٹ کٹ بنانا چاہتی ہے۔ کیا آپ اس کی اجازت دیں گے؟",
    "string-no-accesskey": "نہیں",
    "string-header-wince": "یہ ویب سائٹ آپ کے پروگرامز کی فہرست میں درج ذیل شارٹ کٹ بنانا چاہتی ہے۔ کیا آپ اس کی اجازت دیں گے؟",
    "string-title-simple": "اطلاق کا شارٹ کٹ بنائیں",
    "string-ok-accesskey": "O",
    "string-ok": "ٹھیک ہے",
    "string-cancel-accesskey": "C",
    "string-cancel": "منسوخ",
    "string-startmenu": "اسٹارٹ مینو",
    "string-yes": "ہاں",
    "string-never-allow": "کبھی بھی اس شارٹ کٹ کی اجازت نہ دیں۔",
    "string-yes-accesskey": "ہاں",
    "string-quicklaunch": "فوری شروع کرنے کا بار",
    "string-never-allow-wince": "کبھی بھی اجازت نہ دیں",
    "string-desktop": "ڈیسک ٹاپ",
    "string-title-default": "گیئرز - ڈیسک ٹاپ شارٹ کٹ بنائیں",
    "string-location-query": "درج ذیل مقامات پر شارٹ کٹ بنائیں:"
  },
  "sk": {
    "string-no": "Nie",
    "string-header-desktop": "Táto webová lokalita chce vytvoriť odkaz v počítači. Chcete to povoliť?",
    "string-no-accesskey": "N",
    "string-header-wince": "Táto webová lokalita chce vytvoriť odkaz v zozname programov. Chcete to povoliť?",
    "string-title-simple": "Vytvorte odkazy na aplikácie",
    "string-ok-accesskey": "K",
    "string-ok": "OK",
    "string-cancel-accesskey": "R",
    "string-cancel": "Zrušiť",
    "string-startmenu": "Ponuka Štart",
    "string-yes": "Áno",
    "string-never-allow": "Nikdy nepovoliť tento odkaz",
    "string-yes-accesskey": "O",
    "string-quicklaunch": "Panel s nástrojmi Rýchly prístup",
    "string-never-allow-wince": "Nikdy nepovoliť",
    "string-desktop": "Pracovná plocha",
    "string-title-default": "Gears - Vytvoriť odkaz na pracovnej ploche",
    "string-location-query": "Vytvoriť odkazy na nasledujúcich miestach:"
  },
  "zh-CN": {
    "string-no": "否",
    "string-header-desktop": "该网站要在您的计算机上创建快捷键。 是否允许该操作？",
    "string-no-accesskey": "N",
    "string-header-wince": "该网站要在您的程序列表中创建快捷方式。 是否允许该操作？",
    "string-title-simple": "创建应用程序快捷键",
    "string-ok-accesskey": "O",
    "string-ok": "确定",
    "string-cancel-accesskey": "C",
    "string-cancel": "取消",
    "string-startmenu": "开始菜单",
    "string-yes": "是",
    "string-never-allow": "永不允许该快捷方式",
    "string-yes-accesskey": "Y",
    "string-quicklaunch": "快速启动栏",
    "string-never-allow-wince": "永不允许",
    "string-desktop": "桌面",
    "string-title-default": "Gears - 创建桌面快捷方式",
    "string-location-query": "在以下位置创建快捷键："
  },
  "de": {
    "string-no": "Nein",
    "string-header-desktop": "Für diese Website soll eine Verknüpfung auf Ihrem Computer erstellt werden. Möchten Sie dies zulassen?",
    "string-no-accesskey": "N",
    "string-header-wince": "Für diese Website soll eine Verknüpfung in Ihrer Programmliste erstellt werden. Möchten Sie dies zulassen?",
    "string-title-simple": "Anwendungsverknüpfungen erstellen",
    "string-ok-accesskey": "O",
    "string-ok": "OK",
    "string-cancel-accesskey": "A",
    "string-cancel": "Abbrechen",
    "string-startmenu": "Startmenü",
    "string-yes": "Ja",
    "string-never-allow": "Diese Verknüpfung nie zulassen",
    "string-yes-accesskey": "J",
    "string-quicklaunch": "Schnellstartleiste",
    "string-never-allow-wince": "Nie zulassen",
    "string-desktop": "Desktop",
    "string-title-default": "Gears - Desktopverknüpfung erstellen",
    "string-location-query": "Verknüpfungen unter folgenden Speicherpfaden erstellen:"
  },
  "pl": {
    "string-no": "Nie",
    "string-header-desktop": "Ta witryna internetowa chce utworzyć skrót na Twoim komputerze. Czy chcesz na to zezwolić?",
    "string-no-accesskey": "N",
    "string-header-wince": "Ta witryna chce utworzyć skrót na Twojej liście programów. Czy chcesz na to zezwolić?",
    "string-title-simple": "Utwórz skróty do aplikacji",
    "string-ok-accesskey": "O",
    "string-ok": "OK",
    "string-cancel-accesskey": "A",
    "string-cancel": "Anuluj",
    "string-startmenu": "Menu Start",
    "string-yes": "Tak",
    "string-never-allow": "Nigdy nie zezwalaj na ten skrót",
    "string-yes-accesskey": "T",
    "string-quicklaunch": "Pasek szybkiego uruchamiania",
    "string-never-allow-wince": "Nigdy nie zezwalaj",
    "string-desktop": "Pulpit",
    "string-title-default": "Gears — utwórz skrót na pulpicie",
    "string-location-query": "Utwórz skróty w następujących lokalizacjach:"
  },
  "ms": {
    "string-no": "Tidak",
    "string-header-desktop": "Laman web ini mahu membuat pintasan pada komputer anda. Adakah anda membenarkannya?",
    "string-no-accesskey": "T",
    "string-header-wince": "Laman web ini mahu membuat pintasan dalam senarai atur cara anda. Adakah anda hendak membenarkannya?",
    "string-title-simple": "Buat Pintasan Aplikasi",
    "string-ok-accesskey": "O",
    "string-ok": "OK",
    "string-cancel-accesskey": "B",
    "string-cancel": "Batal",
    "string-startmenu": "Menu mula",
    "string-yes": "Ya",
    "string-never-allow": "Jangan sekali-kali benarkan pintasan ini",
    "string-yes-accesskey": "Y",
    "string-quicklaunch": "Bar lancar cepat",
    "string-never-allow-wince": "Jangan sekali-kali benarkan",
    "string-desktop": "Desktop",
    "string-title-default": "Gear - Buat Pintasan Desktop",
    "string-location-query": "Buat pintasan dalam lokasi yang berikut:"
  },
  "sl": {
    "string-no": "Ne",
    "string-header-desktop": "To spletno mesto želi v vašem računalniku ustvariti bližnjico. Ali želite to dejanje dovoliti?",
    "string-no-accesskey": "N",
    "string-header-wince": "To spletno mesto skuša na seznamu programov ustvariti bližnjico. Ali želite to dejanje dovoliti?",
    "string-title-simple": "Ustvarite bližnjice za programe",
    "string-ok-accesskey": "O",
    "string-ok": "V redu",
    "string-cancel-accesskey": "C",
    "string-cancel": "Prekliči",
    "string-startmenu": "Meni »Start«",
    "string-yes": "Da",
    "string-never-allow": "Nikoli ne dovoli te bližnjice",
    "string-yes-accesskey": "D",
    "string-quicklaunch": "Vrstica za hitri zagon",
    "string-never-allow-wince": "Nikoli ne dovoli",
    "string-desktop": "Namizje",
    "string-title-default": "Gears – Ustvarjanje bližnjice na namizju",
    "string-location-query": "Ustvari bližnjice na teh mestih:"
  },
  "mr": {
    "string-no": "नाही",
    "string-header-desktop": "ही वेबसाइट आपल्या संगणकावर शॉर्टकट तयार करू इच्छिते. यास आपली अनुमती आहे?",
    "string-no-accesskey": "N",
    "string-header-wince": "ही वेबसाइट आपल्या प्रोग्राम्स सूचीमध्ये एक शॉर्टकट तयार करू इच्छित आहे. आपण यास परवानगी देऊ इच्छिता काय?",
    "string-title-simple": "एप्लिकेशन शॉर्टकट तयार करा",
    "string-ok-accesskey": "O",
    "string-ok": "ओके",
    "string-cancel-accesskey": "C",
    "string-cancel": "रद्द करा",
    "string-startmenu": "स्टार्ट मेनू",
    "string-yes": "होय",
    "string-never-allow": "या शॉर्टकटला कधीही परवानगी देऊ नये",
    "string-yes-accesskey": "Y",
    "string-quicklaunch": "क्विक लाँच बार",
    "string-never-allow-wince": "कधीही परवानगी देऊ नये",
    "string-desktop": "डेस्कटॉप",
    "string-title-default": "Gears - डेस्कटॉप शॉर्टकट तयार करा",
    "string-location-query": "खालील स्थानांवर शॉर्टकट तयार करा:"
  },
  "or": {
    "string-no": "ନା",
    "string-header-desktop": "ଏହି ୱେବସାଇଟ୍ ଆପଣଙ୍କ କମ୍ପ୍ୟୁଟରରେ ଏକ ସର୍ଟକଟ ସୃଷ୍ଟି କରିବାକୁ ଚାହୁଁଛି ଆପଣ ଏହାକୁ ଅନୁମତି ଦେବାକୁ ଚାହୁଁଛନ୍ତି ?",
    "string-no-accesskey": "N",
    "string-header-wince": "ଏହି ୱେବସାଇଟ୍ ଆପଣଙ୍କର ପ୍ରୋଗ୍ରାମ୍ ତାଲିକାରେ ଏକ ସର୍ଟକଟ୍ ସୃଷ୍ଟି କରିବାକୁ ଚାହୁଁଛି । ଆପଣ ଏହାକୁ ଅନୁମତି କରିବାକୁ ଚାହୁଁଛନ୍ତି କି?",
    "string-title-simple": "ଅନୁପ୍ରୟୋଗ ସର୍ଟକଟଗୁଡିକ ସୃଷ୍ଟି କରନ୍ତୁ",
    "string-ok-accesskey": "O",
    "string-ok": "ଓକେ",
    "string-cancel-accesskey": "C",
    "string-cancel": "ବାତିଲ୍",
    "string-startmenu": "ଷ୍ଟାର୍ଟ ମେନୁ",
    "string-yes": "ହଁ",
    "string-never-allow": "ଏହି ସର୍ଟକଟ୍ କେବେ ମଧ୍ୟ ଅନୁମତି କରନ୍ତୁ ନାହିଁ",
    "string-yes-accesskey": "Y",
    "string-quicklaunch": "କୁଇକ୍ ଲଞ୍ଚ୍ ବାର୍",
    "string-never-allow-wince": "କେବେ ମଧ୍ୟ ଅନୁମତି କରନ୍ତୁ ନାହିଁ",
    "string-desktop": "ଡେସ୍କଟପ୍",
    "string-title-default": "Gears - ଡେସ୍କଟପ୍ ସର୍ଟକଟ୍ ସୃଷ୍ଟି କରନ୍ତୁ",
    "string-location-query": "ନିମ୍ନ ଅବସ୍ଥାନ ଗୁଡିକରେ ସର୍ଟକଟ ସୃଷ୍ଟି କରନ୍ତୁ:"
  }
};

// Insert all localized strings for the specified locale into the div or span
// matching the id.
function loadI18nStrings(locale) {
  var rtl_languages = ['he', 'ar', 'fa', 'ur'];

  if (!locale) {
    locale = 'en-US';
  } else {
    if (!localized_strings[locale]) {
      // For xx-YY locales, determine what the base locale is.
      var base_locale = locale.split('-')[0];

      if (localized_strings[base_locale]) {
        locale = base_locale;
      } else {
        locale = 'en-US';
      }
    }
  }

  var strings = localized_strings[locale];

  // If the specified locale is an right to left language, change the direction
  // of the page.
  for (index in rtl_languages) {
    if (locale == rtl_languages[index]) {
      document.body.dir = "rtl";
      break;
    }
  }

  // Copy each string to the proper UI element, if it exists.
  for (name in strings) {
    if (name == 'string-html-title') {
      if (!browser.ie_mobile) {
        // IE Mobile dialogs don't have a title bar.
        // Furthermore, document.title is undefined in IE Mobile on WinMo 5.
        // It's also impossible to add properties to the window object.
        // (see http://code.google.com/apis/gears/mobile.html)
        document.title = strings[name];
      }
    } else {
      var element = dom.getElementById(name);
      if (element) {
        element.innerHTML = strings[name];
      }
    }
  }
}

