/*
 * WARNING this file was generated by Titanium's idlgen
 */
 
#ifndef _TITANIUMBOOT_H
#define _TITANIUMBOOT_H

#include "gears/base/common/js_types.h"
#include "gears/appcelerator/ruby_wrapper.h"

namespace TitaniumBoot {
	void DefineClass(RubyInitializer *initializer);
}

#endif