/*
 * WARNING this file was generated by Titanium's idlgen
 */
#include "TitaniumBoot.h"

namespace TitaniumBoot {
	JsObject* jsObject = NULL;
}


extern "C" VALUE TitaniumBoot_confirm (
	VALUE self, 
	VALUE message, 
	VALUE canForce)
{	
	if (TitaniumBoot::jsObject != NULL) {
		JsRootedToken *token;
		VALUE argv[] = {message, canForce};
		
		if (InvokeJsCallback(TitaniumBoot::jsObject, "confirm",
			2, argv, &token))
		{
			return JsRootedTokenToRubyValue(token, JSPARAM_BOOL);
		}
	}
	return Qnil;
}
extern "C" VALUE TitaniumBoot_die (
	VALUE self, 
	VALUE message)
{	
	if (TitaniumBoot::jsObject != NULL) {
		VALUE argv[] = {message};
		
		if (InvokeJsCallback(TitaniumBoot::jsObject, "die",
			1, argv, NULL))
		{
		}
	}
	return Qnil;
}
extern "C" VALUE TitaniumBoot_askForProxy (
	VALUE self)
{	
	if (TitaniumBoot::jsObject != NULL) {
		JsRootedToken *token;
		VALUE argv[] = {};
		
		if (InvokeJsCallback(TitaniumBoot::jsObject, "askForProxy",
			0, argv, &token))
		{
			return JsRootedTokenToRubyValue(token, JSPARAM_STRING16);
		}
	}
	return Qnil;
}
extern "C" VALUE TitaniumBoot_showLoginForm (
	VALUE self)
{	
	if (TitaniumBoot::jsObject != NULL) {
		JsRootedToken *token;
		VALUE argv[] = {};
		
		if (InvokeJsCallback(TitaniumBoot::jsObject, "showLoginForm",
			0, argv, &token))
		{
			return JsRootedTokenToRubyValue(token, JSPARAM_OBJECT);
		}
	}
	return Qnil;
}
extern "C" VALUE TitaniumBoot_showSignupForm (
	VALUE self)
{	
	if (TitaniumBoot::jsObject != NULL) {
		JsRootedToken *token;
		VALUE argv[] = {};
		
		if (InvokeJsCallback(TitaniumBoot::jsObject, "showSignupForm",
			0, argv, &token))
		{
			return JsRootedTokenToRubyValue(token, JSPARAM_OBJECT);
		}
	}
	return Qnil;
}

VALUE TitaniumBoot_Class;
void TitaniumBoot::DefineClass(RubyInitializer *initializer)
{
	TitaniumBoot::jsObject = initializer->GetCallbackObject();
	
	TitaniumBoot_Class = rb_define_class("TitaniumBoot", rb_cObject);
	rb_define_method(TitaniumBoot_Class, "confirm", RUBY_FUNCTION(&TitaniumBoot_confirm), 2);
	rb_define_method(TitaniumBoot_Class, "die", RUBY_FUNCTION(&TitaniumBoot_die), 1);
	rb_define_method(TitaniumBoot_Class, "askForProxy", RUBY_FUNCTION(&TitaniumBoot_askForProxy), 0);
	rb_define_method(TitaniumBoot_Class, "showLoginForm", RUBY_FUNCTION(&TitaniumBoot_showLoginForm), 0);
	rb_define_method(TitaniumBoot_Class, "showSignupForm", RUBY_FUNCTION(&TitaniumBoot_showSignupForm), 0);
}