--- 
:type: widget
:name: app:if
:version: 1.0
:dependencies: 
- :type: websdk
  :version: ">=2.1"
  :name: websdk
:tags: [ logic ]
:licenses: [6]
:description: "app:if is a non-visual control for conditional execution of content based on a Javascript expression"
