require 'fileutils'
require 'zip/zip'
require 'yaml'
require 'erb'
require '../build.rb'

NATIVE_DIR = File.join 'native', (is_mac? ? 'osx' : (is_win? ? 'win32' : 'linux'))

task :default => [:build_shell,:gather]

task :build_shell do
  FileUtils.cd NATIVE_DIR
  if is_mac?
    system 'xcodebuild'
	elsif is_win?
		rake('ti_shell')
  end
end

def gather_mac(zipfile)
	basedir = File.join NATIVE_DIR, 'build', 'Release', 'Titanium.app'
	zipfile.mkdir('Titanium.app')
      
	dofiles(basedir) do |f|
		filename = f.to_s
		zipfile.add(File.join('Titanium.app', filename), File.join(basedir, filename))
	end
end

def gather_win(zipfile)
	zipfile.add('ti_shell.exe', File.join(NATIVE_DIR, 'ti_shell', 'src', 'build', 'Release', 'ti_shell.exe'))
end

task :gather do
  FileUtils.cd RUNTIME_DIR
	template = nil
	File.open('build.yml') { |f| template = ERB.new(f.read()) }

	build_yml = template.result(binding)
  build = YAML::load(build_yml)
  filename = File.join(STAGE_DIR, "titanium_runtime_" + build[:version].to_s + "_" + platform_string + ".zip")
  
  if File.exists?(filename)
    puts "rm #{filename}"
    FileUtils.rm filename
  end
  
  Zip::ZipFile.open(filename, Zip::ZipFile::CREATE) {
    |zipfile|
    
    if is_mac?
			gather_mac(zipfile)
		elsif is_win?
			gather_win(zipfile)
    end
    
    Dir["src/**/*"].each do |filepath|
      filename = File.basename(filepath)
      zipfile.add(filename, filepath)
    end
 
    zipfile.mkdir("support")
		Dir["support/*"].each do |filepath|
			filename = File.basename(filepath)
			if filename !~ /(osx|win32|linux)/
      	zipfile.add(File.join('support', filename), File.join('support', filename))
			end
		end
 
    dofiles("support/" + platform_string) do |f|
      filename = f.to_s
     	zipfile.add(File.join('support', platform_string, filename), File.join('support', platform_string, filename))
    end
    
    zipfile.get_output_stream('build.yml') { |f| f.write(build_yml) }
    zipfile.add('install.rb', 'install.rb')
  }
end
