#!/usr/bin/env python
import os.path as path
Import('tiBuild')
Import('build')

Env = tiBuild.env.Clone()
Env.Append(FRAMEWORKS=['Cocoa'])

s = Env.Program(tiBuild.dir + '/klaunch', Glob('*.m') + Glob('*.cpp'))

Execute(Mkdir(tiBuild.dir+'/launcher'))

for i in Glob('*.xib'):
	base = path.splitext(path.basename(str(i)))[0]
	Env.AddPostAction(s, 'ibtool --errors --warnings --notices --output-format human-readable-text --compile '+tiBuild.dir + '/launcher/'+ base+'.nib '+str(i))
	

for i in Glob('*.plist'):
   base = path.splitext(path.basename(str(i)))[0]
   Env.AddPostAction(s, 'cp '+str(i)+' '+tiBuild.dir + '/launcher')
