#!/usr/bin/env python
import os.path as path
Import('tiBuild')


OSX_SDK = '/Developer/SDKs/MacOSX10.4u.sdk'
OSX_UNIV_COMPILER = '-isysroot '+OSX_SDK+' -arch i386'
OSX_UNIV_LINKER = '-isysroot '+OSX_SDK+' -syslibroot,'+OSX_SDK

Env = tiBuild.env.Clone()
Env.Append(FRAMEWORKS=['Foundation','Cocoa'])
Env.Append(CCFLAGS=OSX_UNIV_COMPILER)
Env.Append(LDFLAGS=OSX_UNIV_LINKER)

s = Env.Program(tiBuild.dir + '/klaunch', Glob('*.m') + Glob('*.cpp'))

Execute(Mkdir(tiBuild.dir+'/launcher'))

for i in Glob('*.xib'):
	base = path.splitext(path.basename(str(i)))[0]
	Env.AddPostAction(s, 'ibtool --errors --warnings --notices --output-format human-readable-text --compile '+tiBuild.absdir + '/launcher/'+ base+'.nib '+str(i))
	

for i in Glob('*.plist'):
   base = path.splitext(path.basename(str(i)))[0]
   Env.AddPostAction(s, 'cp '+str(i)+' '+tiBuild.absdir + '/launcher')
