#!/usr/bin/env python
import os

Import("tiBuild")
Import('build')

tiBuild.add_thirdparty(build.env, 'poco')

env = tiBuild.env.Clone();
env.Append(CPPDEFINES = ('TITANIUM_APP_API_EXPORT', 1))
env.Append(CPPPATH = ['#kroll'])

if tiBuild.is_win32():
	env.Append(CPPPATH = ['#kroll/thirdparty/win32/libxml/include', '#kroll/thirdparty/win32/icu/include'])
	env.Append(LIBPATH = ['#kroll/thirdparty/win32/webkit/lib'])
	env.Append(LIBS=['libxml2', 'pthreadVC2'])
else:
	if os.environ.has_key('PKG_CONFIG_PATH'):
		env.AppendENVPath('PKG_CONFIG_PATH', os.environ['PKG_CONFIG_PATH'])
	env.ParseConfig('pkg-config --cflags --libs libxml-2.0')


s = env.SharedLibrary(target = tiBuild.dir + '/tiappmodule', source = Glob('*.cpp') + Glob('Properties/*.cpp'))

