#!/usr/bin/env python

import os.path as p, os 
import glob, distutils.dir_util as dir_util
Import('build')

t = build.env.PackageApp('#testapp-target',
	[Dir('Resources'), 'tiapp.xml'],
	SHORTNAME='testapp',
	FULLNAME='Titanium Test App',
	ID='com.titaniumapp.testapp',
	GUID='D36DD8BA-D092-4F20-9073-EB613BFB8F46')
Depends(t, build.targets)
Alias('testapp', t)

