#!/usr/bin/env python

import os.path as p, os, futils
import glob, distutils.dir_util as dir_util
from app import App
from subprocess import Popen
Import('build')


t = build.env.PackageApp('#unittest-target',
	[Dir('Resources'), 'tiapp.xml'],
	SHORTNAME='unittest',
	FULLNAME='Titanium Unit Test App',
	ID='com.titaniumapp.unittest.driver',
	GUID='D83B08F4-B43B-4909-9FEE-336CDB44750B')
Depends(t, build.build_targets + build.staging_targets)
Alias('unittest', t)

