#!/usr/bin/env python
import os.path as path, distutils.dir_util as dir_util

Import('build')

Env = build.env.Clone()
Env.Append(FRAMEWORKS=['Cocoa','SystemConfiguration','IOKit'])
Env.Append(LIBS=['curl'])
Env.Append(CPPFLAGS=['-Wno-error']) #turn off warnings, CURLHandle has a lot
Env.Append(CPPPATH=[build.kroll_source_dir+'/api'])

sources = Glob('*.m') + Glob('*.mm')
sources.append(path.join(build.kroll_source_dir,'api','file_utils.cpp'))
s = Env.Program('net_installer', sources)

# TODO: is there some way to read the incomming build_dir?
# If so we should do that instead.
out_dir = path.join(build.dir, 'net_installer')

for i in Glob('English.lproj/*.xib'):
	base = path.splitext(path.basename(str(i)))[0]
	Env.AddPostAction(s, 'ibtool --errors --warnings --notices --output-format human-readable-text --compile '+out_dir+'/'+base+'.nib '+str(i))
	

for i in Glob('*.plist'): 
	base = path.splitext(path.basename(str(i)))[0]
	Env.AddPostAction(s, 'cp -f '+str(i)+' '+out_dir)
