#!/usr/bin/env python
import os.path as path

Import('build')

Env = build.env.Clone()
Env.Append(FRAMEWORKS=['Cocoa','SystemConfiguration','IOKit'])
Env.Append(LIBS=['curl'])
Env.Append(CPPFLAGS=['-Wno-error']) #turn off warnings, CURLHandle has a lot
Env.Append(CPPPATH=[build.kroll_source_dir+'/api'])

s = Env.Program(build.dir + '/installer', Glob('*.m')+[build.dir+'/api/file_utils.os'])

for i in Glob('English.lproj/*.xib'):
	base = path.splitext(path.basename(str(i)))[0]
	Env.AddPostAction(s, 'ibtool --errors --warnings --notices --output-format human-readable-text --compile '+build.dir + '/tinstaller/'+ base+'.nib '+str(i))
	

for i in Glob('*.plist'): 
   base = path.splitext(path.basename(str(i)))[0]
   Env.AddPostAction(s, 'cp '+str(i)+' '+build.dir + '/tinstaller')
