/*
 * WARNING this file was generated by Titanium's idlgen
 */
 
#ifndef _APP_COMMAND_H
#define _APP_COMMAND_H

#include "gears/base/common/js_types.h"
#include "gears/base/common/dispatcher.h"

extern "C" {
#include <ruby.h>
}


class RubyWrapper;

class AppCommand : public ModuleImplBaseClass {
public:
	AppCommand();
	void DefineClasses();
	static const std::string kModuleName;
	JsObject* jsObject;
	JsObject* appOptions;
	
	void App (JsCallContext *context);
	void Sleep (JsCallContext *context);
	

private:
	~AppCommand();
	DISALLOW_EVIL_CONSTRUCTORS(AppCommand);
};

#endif