#!/usr/bin/env python
import os, os.path as p
Import('build')

SConscript(p.join('appinstaller', 'SConscript'))
SConscript(p.join('net_installer', 'SConscript'))
SConscript(p.join('developer', 'SConscript'))

if build.is_win32():
	SConscript(p.join('self_extractor', 'SConscript'))
