#!/usr/bin/env python

import os.path as p, os 
import glob, distutils.dir_util as dir_util
Import('build')

t = build.env.PackageApp('#uploader-target',
	[Dir('Resources'), 'tiapp.xml'],
	FULLNAME='Titanium Release Uploader',
	ID='com.titaniumapp.uploader',
	GUID='925AE1B0-180B-11DE-8C30-0800200C9A66')
Depends(t, build.build_targets + build.staging_targets)
Alias('uploader', t)
