#!/usr/bin/env python
import os
Import('build')

env = build.env.Clone();
env.Append(CPPDEFINES = ('TITANIUM_PLATFORM_API_EXPORT', 1))
env.Append(CPPPATH = ['#kroll'])

if build.is_osx():
	build.add_thirdparty(env, 'poco', True)
	env.Append(LIBS=['kroll'])
else:
	build.add_thirdparty(env, 'poco')

if build.is_win32():
    env.Append(CCFLAGS=['/MD'])
    env.Append(LIBS=['Advapi32'])
    env.Append(CPPDEFINES = ('WIN32_LEAN_AND_MEAN',1))

m = build.add_module('ti.Platform')
s = env.SharedLibrary(target = m.build_dir + '/tiplatformmodule', source = Glob('*.cpp'))
s = env.SharedLibrary(target = build.dir + '/tiplatformmodule', source = Glob('*.cpp'))
