#!/usr/bin/env python
import os

Import("tiBuild")
Import('build')

env = tiBuild.env.Clone();
env.Append(CPPDEFINES = ('TITANIUM_PLATFORM_API_EXPORT', 1))
env.Append(CPPPATH = ['#kroll'])

if tiBuild.is_osx():
	tiBuild.add_thirdparty(env, 'poco', True)
	env.Append(LIBS=['kroll'])
else:
	tiBuild.add_thirdparty(env, 'poco')

if tiBuild.is_win32():
    env.Append(CCFLAGS=['/MD'])
    env.Append(LIBS=['Advapi32'])
    env.Append(CPPDEFINES = ('WIN32_LEAN_AND_MEAN',1))

s = env.SharedLibrary(target = tiBuild.dir + '/tiplatformmodule', source = Glob('*.cpp'))
