#!/usr/bin/env python
Import('build')
import os.path as p

name = 'titanium_runtime'
version = build.version
appid ='com.titaniumapp.installer.runtime'

runtime_libs = ['kroll', 'khost']
third_party = ['webkit', 'poco']

modules = build.modules

manifest_text="""
#appname: %s
#appid: %s
runtime: %s
""" % (name, appid, version)

for m in modules:
	manifest_text += "%s: %s\n" % (m.name, build.version)

vars = 'vars build name version runtime_libs '
vars += ' third_party modules appid manifest_text'
if build.is_osx():
	SConscript('SConscript.osx', vars)

if build.is_linux():
	SConscript('SConscript.linux', vars)

if build.is_win32():
	SConscript('SConscript.win32', vars)

