#!/usr/bin/env python
import os

Import('build')
Import("tiBuild")

env = tiBuild.env.Clone();
env.Append(CPPDEFINES = ('TITANIUM_DESKTOP_API_EXPORT', 1))
env.Append(CPPPATH = ['#kroll'])

if tiBuild.is_osx():
	tiBuild.add_thirdparty(env, 'poco', True)
	env.Append(LIBS=['kroll'])
else:
	tiBuild.add_thirdparty(env, 'poco')

sources = Glob('*.cpp')

if tiBuild.is_osx():
	env.Append(FRAMEWORKS = ['Cocoa'])
	sources+=Glob('osx/*.cpp')
elif tiBuild.is_win32():
	env.Append(LIBS=['shell32', 'user32', 'comdlg32', 'ole32'])
	env.Append(CPPDEFINES = ('WIN32_LEAN_AND_MEAN', 1))
	sources+=Glob('win32/*.cpp')
elif tiBuild.is_linux():
	sources+=Glob('linux/*.cpp')
	
	
s = env.SharedLibrary(target = tiBuild.dir + '/tidesktopmodule', source = sources)

