#!/usr/bin/env python
import os

Import("tiBuild")
Import('build')

env = tiBuild.env.Clone();
env.Append(CPPDEFINES = {'TITANIUM_API_EXPORT' : 1})
env.Append(CPPPATH = ['#kroll'])

if build.is_osx():
	OSX_SDK = '/Developer/SDKs/MacOSX10.4u.sdk'
	OSX_UNIV_COMPILER = '-isysroot '+OSX_SDK+' -arch ppc -arch i386'
	OSX_UNIV_LINKER = '-isysroot '+OSX_SDK+' -syslibroot,'+OSX_SDK
	env.Append(FRAMEWORKS = ['Cocoa','IOKit'])
	env.Append(CCFLAGS = ['-x', 'objective-c++'])
	env.Append(CCFLAGS=OSX_UNIV_COMPILER)
	env.Append(LDFLAGS=OSX_UNIV_LINKER)


s = env.SharedLibrary(target = tiBuild.dir + '/tidesktopmodule', source = Glob('*.cpp'))

