
Import('build')

env = build.env.Clone()

commandName = "titanium_sdk"
if build.is_win32():
	commandName +=".exe"

sources = Glob('*.py') + Glob('Resources/*')
sources += 'manifest'
Command(build.dir + "/" + commandName, sources,[

])