#!/usr/bin/env python
import os

Import("tiBuild")

env = tiBuild.env.Clone();
env.Append(CPPDEFINES = {'TITANIUM_MENU_API_EXPORT' : 1})
env.Append(CPPPATH = ['#kroll'])
tiBuild.add_thirdparty(env, 'poco')

sources = Glob('*.cpp')

if tiBuild.is_osx():
	env.Append(FRAMEWORKS = ['Cocoa'])
	sources += Glob('osx/*.cpp') + Glob('osx/*.mm')
elif tiBuild.is_win32():
	env.Append(LIBS = ['user32'])
	env.Append(CPPDEFINES = {'WIN32_LEAN_AND_MEAN':1})
	sources += Glob('win32/*.cpp')
elif tiBuild.is_linux():
	sources += Glob('linux/*.cpp')


s = env.SharedLibrary(target = tiBuild.dir + '/timenumodule', source = sources)
