#!/usr/bin/env python
import os

Import("tiBuild")

env = tiBuild.env.Clone();
env.Append(CPPDEFINES = {'TITANIUM_MENU_API_EXPORT' : 1})
env.Append(CPPPATH = ['#kroll'])
tiBuild.add_thirdparty(env, 'poco')

if tiBuild.is_osx():
	env.Append(FRAMEWORKS = ['Cocoa'])


s = env.SharedLibrary(target = tiBuild.dir + '/timenumodule', source = Glob('*.cpp'))
