#!/usr/bin/env python

import os.path as p, os 
import glob, distutils.dir_util as dir_util
Import('build')
Import('run')

t = build.env.PackageApp('#apivalidator-target',
	[Dir('Resources'), 'tiapp.xml'],
	SHORTNAME='apivalidator',
	FULLNAME='Titanium API Validator',
	ID='com.titaniumapp.apivalidator',
	GUID='F28A8274-1000-11DE-AE9B-587656D89593')
Depends(t, build.build_targets + build.staging_targets)
Alias('apivalidator', t)
Alias('testsuite', t)
