--- 
:type: widget
:name: app:content
:version: 1.0.2
:dependencies: 
- :type: websdk
  :version: ">=2.1"
  :name: websdk
:tags: [ ]
:licenses: [6]
:description: "app:content allows you to load external HTML content. this content can be parameterized and can be loaded on-demand or when the page is first loaded"
